import {build} from 'esbuild';
import {createServer} from 'node:http';
import {mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';

const playwright=await import(process.env.FCP_PLAYWRIGHT_PACKAGE??'@playwright/test');
const {chromium}=playwright.default??playwright;
const here=dirname(fileURLToPath(import.meta.url));
const temporary='/private/tmp/fai-ui-pr3/harness';
await mkdir(temporary,{recursive:true});
await build({entryPoints:[join(here,'pr3-fixture-app.tsx')],bundle:true,format:'esm',platform:'browser',outfile:join(temporary,'fixture.js'),jsx:'automatic',plugins:[{name:'fixture-runtime',setup(builder){builder.onResolve({filter:/^next\/navigation$/},()=>({path:'next/navigation',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},()=>({loader:'js',contents:`export const useRouter=()=>({refresh(){},push(){},replace(){}});`}));builder.onResolve({filter:/^next\/link$/},()=>({path:'next/link',namespace:'fixture-link'}));builder.onLoad({filter:/.*/,namespace:'fixture-link'},()=>({loader:'js',resolveDir:here,contents:`import {createElement} from 'react';export default function Link({href,children,...props}){return createElement('a',{href,...props},children)}`}));builder.onResolve({filter:/^node:crypto$/},()=>({path:'node:crypto',namespace:'fixture-crypto'}));builder.onLoad({filter:/.*/,namespace:'fixture-crypto'},()=>({loader:'js',contents:`export function createHash(){let value='';return {update(next){value+=String(next);return this},digest(){let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return (hash>>>0).toString(16).padStart(8,'0').repeat(8)}}}`}));}}]});
const css=(await Promise.all(['../../app/styles/controls.css','../../app/styles/tokens.css','../../app/styles/foundation.css','../../app/styles/projects.css'].map((path)=>readFile(join(here,path),'utf8')))).join('\n');
const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/fixture.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>';
const server=createServer(async(request,response)=>{if(request.url==='/fixture.js'){response.setHeader('content-type','text/javascript');response.end(await readFile(join(temporary,'fixture.js')));}else if(request.url==='/fixture.css'){response.setHeader('content-type','text/css');response.end(css);}else{response.setHeader('content-type','text/html');response.end(html);}});
await new Promise((resolve)=>server.listen(3100,'127.0.0.1',resolve));
const output=process.env.FCP_CAPTURE_DIR??'artifacts/ui-review/after/pr3';
const states=['chats-configured','chats-unconfigured','systems-configured','systems-unconfigured','systems-installing','systems-auth-required','systems-offline','systems-degraded','roles-read-only','empty'];
const viewports=[['1440x900',1440,900],['1280x800',1280,800],['390x844',390,844]];
await mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const [name,width,height] of viewports){const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'});for(const state of states){await page.goto(`http://127.0.0.1:3100/?state=${state}`,{waitUntil:'networkidle'});await page.locator('#root > *').waitFor({state:'attached'});if(!(await page.locator('#root').innerText()).trim())throw new Error(`empty fixture: ${state}`);if(name==='390x844'){const trigger=page.locator('.fcp-mobile-menu > summary');await trigger.click();await page.locator('.fcp-mobile-menu-body').getByRole('button',{name:'Выйти'}).waitFor({state:'visible'});await trigger.click();}await page.screenshot({path:`${output}/${state}-${name}.png`,fullPage:false});}await page.context().setOffline(true);await page.waitForTimeout(20);await page.screenshot({path:`${output}/offline-${name}.png`,fullPage:false});await page.context().setOffline(false);await page.close();}}finally{await browser.close();await new Promise((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));}
