import {build} from 'esbuild';
import {createServer} from 'node:http';
import {mkdir,readdir,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';

const playwright=await import(process.env.FCP_PLAYWRIGHT_PACKAGE??'@playwright/test');
const {chromium}=playwright.default??playwright;

const here=dirname(fileURLToPath(import.meta.url));
const temporary='/private/tmp/fai-ui-pr2/harness';
await mkdir(temporary,{recursive:true});
await build({entryPoints:[join(here,'pr2-fixture-app.tsx')],bundle:true,format:'esm',platform:'browser',outfile:join(temporary,'fixture.js'),jsx:'automatic',plugins:[{name:'fixture-runtime',setup(builder){builder.onResolve({filter:/^next\/navigation$/},()=>({path:'next/navigation',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},()=>({loader:'js',contents:`export const usePathname=()=>'/overview';export const useRouter=()=>({refresh(){},push(){},replace(){}});`}));builder.onResolve({filter:/^next\/link$/},()=>({path:'next/link',namespace:'fixture-link'}));builder.onLoad({filter:/.*/,namespace:'fixture-link'},()=>({loader:'js',resolveDir:here,contents:`import {createElement} from 'react';export default function Link({href,children,...props}){return createElement('a',{href,...props},children)}`}));builder.onResolve({filter:/^node:crypto$/},()=>({path:'node:crypto',namespace:'fixture-crypto'}));builder.onLoad({filter:/.*/,namespace:'fixture-crypto'},()=>({loader:'js',contents:`export function createHash(){let value='';return {update(next){value+=String(next);return this},digest(){let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return (hash>>>0).toString(16).padStart(8,'0').repeat(8)}}}`}));}}]});
const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/fixture.css"><style>*{caret-color:transparent!important}</style></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>';
const css=(await Promise.all(['../../app/styles/controls.css','../../app/styles/tokens.css','../../app/styles/foundation.css','../../app/styles/projects.css'].map((path)=>readFile(join(here,path),'utf8')))).join('\n');
const server=createServer(async(request,response)=>{if(request.url==='/fixture.js'){response.setHeader('content-type','text/javascript');response.end(await readFile(join(temporary,'fixture.js')));}else if(request.url==='/fixture.css'){response.setHeader('content-type','text/css');response.end(css);}else{response.setHeader('content-type','text/html');response.end(html);}});
await new Promise((resolve)=>server.listen(3098,'127.0.0.1',resolve));
if(process.env.FCP_CAPTURE_SERVE==='1')await new Promise(()=>{});
const output=process.env.FCP_CAPTURE_DIR??'/private/tmp/fai-ui-pr2/after';
const compareDirectory=process.env.FCP_CAPTURE_COMPARE_DIR;
if(compareDirectory!==undefined&&compareDirectory===output)throw new Error('FCP_CAPTURE_DIR must differ from FCP_CAPTURE_COMPARE_DIR');
const viewports=[['1440x900',1440,900],['1280x800',1280,800],['390x844',390,844]];
const states=(process.env.FCP_CAPTURE_STATES??'login,overview,tasks,tasks-detail,tasks-unknown,tasks-stale,tasks-empty,process,process-unconfigured,process-read-only').split(',');
async function capture(page,options){await page.waitForTimeout(50);return page.screenshot(options);}
async function inspectProcessDialog(page,name,state){const editable=state!=='process-read-only';const trigger=page.getByRole('button',{name:new RegExp(`${editable?'Настроить':'Просмотреть'} ИИ-агента: ASCON`)});await trigger.click();const dialog=page.getByRole('dialog',{name:'Настройка ИИ-агента: ASCON'});await dialog.waitFor({state:'visible'});if(await dialog.getAttribute('aria-modal')!=='true')throw new Error('agent routing dialog is not modal');const taskClass=dialog.getByLabel('Класс задач');if(await taskClass.evaluate((element)=>document.activeElement===element)!==true)throw new Error('agent routing dialog did not focus task class');for(const label of ['Класс задач','Исполнитель','Модель','Рассуждение'])await dialog.getByLabel(label).waitFor({state:'visible'});if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error(`horizontal overflow: agent routing dialog ${name} ${state}`);await capture(page,{path:`${output}/agent-routing-dialog-${state}-${name}.png`,fullPage:false});await page.keyboard.press('Shift+Tab');if(await dialog.getByRole('button',{name:editable?'Закрыть':'Закрыть'}).evaluate((element)=>document.activeElement===element)!==true)throw new Error('agent routing dialog does not wrap reverse tab focus');await page.keyboard.press('Tab');if(await taskClass.evaluate((element)=>document.activeElement===element)!==true)throw new Error('agent routing dialog does not wrap tab focus');await page.keyboard.press('Escape');if(await trigger.evaluate((element)=>document.activeElement===element)!==true)throw new Error('agent routing dialog did not restore trigger focus');}
async function captureRoutingCommand(page,name){const trigger=page.getByRole('button',{name:'Настроить ИИ-агента: ASCON'});await page.route('**/api/projects/project-ascon/agent-routing',async(route)=>{const body=route.request().postDataJSON();if(!body.policy||body.policy.routes.length!==9||!body.idempotencyKey)throw new Error('routing payload contract changed');await new Promise((resolve)=>setTimeout(resolve,400));await route.fulfill({status:200,contentType:'application/json',body:'{}'});});await trigger.click();const dialog=page.getByRole('dialog',{name:'Настройка ИИ-агента: ASCON'});await dialog.getByLabel('Класс задач').selectOption('architecture_design');await dialog.getByLabel('Исполнитель').selectOption('codex-cli');await dialog.getByRole('button',{name:'Сохранить'}).click();await capture(page,{path:`${output}/agent-routing-pending-${name}.png`,fullPage:false});await page.getByText('Настройка сохранена.').waitFor();await capture(page,{path:`${output}/agent-routing-success-${name}.png`,fullPage:false});await page.unroute('**/api/projects/project-ascon/agent-routing');await dialog.getByRole('button',{name:'Закрыть'}).click();await page.route('**/api/projects/project-ascon/agent-routing',(route)=>route.fulfill({status:500,contentType:'application/json',body:'{"error":"routing_denied"}'}));await trigger.click();await dialog.getByRole('button',{name:'Сохранить'}).click();await dialog.getByRole('alert').waitFor();await capture(page,{path:`${output}/agent-routing-error-${name}.png`,fullPage:false});await page.unroute('**/api/projects/project-ascon/agent-routing');}
await mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const waitUntil=process.env.FCP_CAPTURE_WAIT_UNTIL??'networkidle';try{for(const [name,width,height] of viewports){const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'});const errors=[];page.on('pageerror',(error)=>errors.push(error.message));for(const state of states){await page.goto(`http://127.0.0.1:3098/?state=${state}`,{waitUntil});await page.locator('#root > *').waitFor({state:'attached'});if(errors.length>0)throw new Error(errors.join('\n'));const text=(await page.locator('#root').innerText()).trim();if(!text)throw new Error(`empty fixture for ${state}`);if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error(`horizontal overflow: ${state} ${name}`);if(state==='process-unconfigured'&&(await page.locator('.fcp-c-project-section').first().getByRole('button').count())!==0)throw new Error('unconfigured process exposes mutations');if(state==='tasks'){const selector=page.locator('.fcp-c-task-project-selector');await selector.locator('summary').click();if(!await selector.evaluate((element)=>element.open))throw new Error('project selector did not open');await selector.locator('nav a').nth(1).evaluate((link)=>{link.addEventListener('click',(event)=>event.preventDefault(),{once:true});link.click();});if(await selector.evaluate((element)=>element.open))throw new Error('project selector must close after selection');await page.waitForTimeout(50);await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());}if(name==='390x844'&&state==='tasks'){const ready=page.getByRole('tab',{name:/Ready/});await ready.press('ArrowRight');if(await page.getByRole('tab',{name:/In Dev/}).getAttribute('aria-selected')!=='true')throw new Error('ArrowRight must select In Dev');await page.getByRole('tab',{name:/In Dev/}).press('End');if(await page.getByRole('tab',{name:/Done/}).getAttribute('aria-selected')!=='true')throw new Error('End must select Done');await page.locator('.fcp-c-task-mobile-stages').evaluate((element)=>{element.scrollLeft=element.scrollWidth;});await page.waitForTimeout(50);await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());}console.log(`${state}-${name}: ${text.slice(0,80)}`);await capture(page,{path:`${output}/${state}-${name}.png`,fullPage:false});if(state==='process'||state==='process-read-only')await inspectProcessDialog(page,name,state);}if(name==='1440x900'&&states.includes('process')){await page.goto('http://127.0.0.1:3098/?state=process',{waitUntil});await captureRoutingCommand(page,name);}await page.close();}}finally{await browser.close();await new Promise((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));}

if(compareDirectory!==undefined){
  const pngNames=async(directory)=>(await readdir(directory)).filter((name)=>name.endsWith('.png')).sort();
  const actual=await pngNames(output);
  const expected=await pngNames(compareDirectory);
  if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`visual baseline file set differs: actual=${actual.join(',')} expected=${expected.join(',')}`);
  for(const name of actual){
    const [candidate,golden]=await Promise.all([readFile(join(output,name)),readFile(join(compareDirectory,name))]);
    const digest=(value)=>createHash('sha256').update(value).digest('hex');
    if(digest(candidate)!==digest(golden))throw new Error(`visual baseline mismatch: ${name}`);
  }
  console.log(`visual baseline compare passed: ${actual.length} PNGs`);
}
