import {build} from 'esbuild';
import {createServer} from 'node:http';
import {mkdir,readdir,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';

const playwright=await import(process.env.FCP_PLAYWRIGHT_PACKAGE??'@playwright/test');
const {chromium}=playwright.default??playwright;
const here=dirname(fileURLToPath(import.meta.url));
const temporary='/private/tmp/fai-ui-pr3/harness';
await mkdir(temporary,{recursive:true});
await build({entryPoints:[join(here,'pr3-fixture-app.tsx')],bundle:true,format:'esm',platform:'browser',outfile:join(temporary,'fixture.js'),jsx:'automatic',plugins:[{name:'fixture-runtime',setup(builder){builder.onResolve({filter:/^next\/navigation$/},()=>({path:'next/navigation',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},()=>({loader:'js',contents:`export const useRouter=()=>({refresh(){},push(){},replace(){}});`}));builder.onResolve({filter:/^next\/link$/},()=>({path:'next/link',namespace:'fixture-link'}));builder.onLoad({filter:/.*/,namespace:'fixture-link'},()=>({loader:'js',resolveDir:here,contents:`import {createElement} from 'react';export default function Link({href,children,...props}){return createElement('a',{href,...props},children)}`}));builder.onResolve({filter:/^node:crypto$/},()=>({path:'node:crypto',namespace:'fixture-crypto'}));builder.onLoad({filter:/.*/,namespace:'fixture-crypto'},()=>({loader:'js',contents:`export function createHash(){let value='';return {update(next){value+=String(next);return this},digest(){let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return (hash>>>0).toString(16).padStart(8,'0').repeat(8)}}}`}));}}]});
const css=(await Promise.all(['../../app/styles/controls.css','../../app/styles/tokens.css','../../app/styles/foundation.css','../../app/styles/projects.css'].map((path)=>readFile(join(here,path),'utf8')))).join('\n');
const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/fixture.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>';
const server=createServer(async(request,response)=>{if(request.url==='/fixture.js'){response.setHeader('content-type','text/javascript');response.end(await readFile(join(temporary,'fixture.js')));}else if(request.url==='/fixture.css'){response.setHeader('content-type','text/css');response.end(css);}else{response.setHeader('content-type','text/html');response.end(html);}});
await new Promise((resolve)=>server.listen(3100,'127.0.0.1',resolve));
const output=process.env.FCP_CAPTURE_DIR??'artifacts/ui-review/after/pr3';
const compareDirectory=process.env.FCP_CAPTURE_COMPARE_DIR;
if(compareDirectory!==undefined&&compareDirectory===output)throw new Error('FCP_CAPTURE_DIR must differ from FCP_CAPTURE_COMPARE_DIR');
const states=['chats-configured','chats-unconfigured','systems-configured','systems-unconfigured','systems-installing','systems-auth-required','systems-offline','systems-degraded','roles-owner','roles-read-only','roles-empty','empty'];
const viewports=[['1440x900',1440,900],['1280x800',1280,800],['390x844',390,844]];
async function inspectRolesDialog(page,name){const edit=page.getByRole('button',{name:'Изменить членство: Владимир Филатов · ASCON'});await edit.click();const dialog=page.getByRole('dialog',{name:'Изменить: Владимир Филатов'});await dialog.waitFor({state:'visible'});if(await dialog.getAttribute('aria-modal')!=='true')throw new Error('membership dialog is not modal');if(await page.evaluate(()=>document.activeElement?.tagName)!=='SELECT')throw new Error('membership dialog did not focus its role field');await page.screenshot({path:`${output}/roles-edit-dialog-${name}.png`,fullPage:false});await page.keyboard.press('Shift+Tab');if(await page.getByRole('button',{name:'Отмена'}).evaluate((element)=>document.activeElement===element)!==true)throw new Error('membership dialog does not wrap reverse tab focus');await page.keyboard.press('Tab');if(await page.evaluate(()=>document.activeElement?.tagName)!=='SELECT')throw new Error('membership dialog does not wrap tab focus');await page.keyboard.press('Escape');if(await edit.evaluate((element)=>document.activeElement===element)!==true)throw new Error('membership dialog did not restore trigger focus');const add=page.getByRole('button',{name:'Добавить участника: ASCON'});await add.click();const addDialog=page.getByRole('dialog',{name:'Добавить участника'});await addDialog.waitFor({state:'visible'});if(await addDialog.getAttribute('aria-modal')!=='true')throw new Error('add dialog is not modal');const existing=addDialog.getByRole('button',{name:'Выбрать сотрудника'});if(await existing.evaluate((element)=>document.activeElement===element)!==true)throw new Error('add dialog did not focus its first action');if(name==='1440x900'||name==='390x844')await page.screenshot({path:`${output}/roles-add-dialog-${name}.png`,fullPage:false});await addDialog.getByRole('button',{name:'Добавить нового'}).click();const nameField=addDialog.getByLabel('Имя');await nameField.waitFor({state:'visible'});for(const label of ['Имя','Роль','GitHub ID','Telegram ID','Bitrix24 ID'])await addDialog.getByLabel(label).waitFor({state:'visible'});if(await nameField.evaluate((element)=>document.activeElement===element)!==true)throw new Error('new-member form did not focus its name field');if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error(`horizontal overflow: new member ${name}`);if(name==='1440x900'||name==='390x844')await page.screenshot({path:`${output}/roles-add-new-${name}.png`,fullPage:false});await page.keyboard.press('Escape');if(await add.evaluate((element)=>document.activeElement===element)!==true)throw new Error('add dialog did not restore trigger focus');}
async function captureMembershipCommands(page,name){const edit=page.getByRole('button',{name:'Изменить членство: Владимир Филатов · ASCON'});await page.route('**/api/access/memberships/**',async(route)=>{await new Promise((resolve)=>setTimeout(resolve,400));await route.fulfill({status:200,contentType:'application/json',body:'{}'});});await edit.click();await page.getByRole('dialog',{name:'Изменить: Владимир Филатов'}).getByRole('button',{name:'Сохранить'}).click();await page.screenshot({path:`${output}/roles-command-pending-${name}.png`,fullPage:false});await page.getByText('Членство обновлено.').waitFor();await page.screenshot({path:`${output}/roles-command-success-${name}.png`,fullPage:false});await page.unroute('**/api/access/memberships/**');await page.route('**/api/access/memberships/**',(route)=>route.fulfill({status:500,contentType:'application/json',body:'{"error":"membership_denied"}'}));await page.getByRole('button',{name:'Отмена'}).click();await edit.click();await page.getByRole('dialog',{name:'Изменить: Владимир Филатов'}).getByRole('button',{name:'Сохранить'}).click();await page.getByRole('alert').waitFor();await page.screenshot({path:`${output}/roles-command-error-${name}.png`,fullPage:false});await page.unroute('**/api/access/memberships/**');}
await mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const [name,width,height] of viewports){const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'});for(const state of states){await page.goto(`http://127.0.0.1:3100/?state=${state}`,{waitUntil:'networkidle'});await page.locator('#root > *').waitFor({state:'attached'});if(!(await page.locator('#root').innerText()).trim())throw new Error(`empty fixture: ${state}`);if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error(`horizontal overflow: ${state} ${name}`);if(name==='390x844'){const trigger=page.locator('.fcp-mobile-menu > summary');await trigger.click();await page.locator('.fcp-mobile-menu-body').getByRole('button',{name:'Выйти'}).waitFor({state:'visible'});await trigger.click();await page.mouse.move(0,height-1);await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());}await page.screenshot({path:`${output}/${state}-${name}.png`,fullPage:false});if(state==='roles-owner')await inspectRolesDialog(page,name);}if(name==='1440x900'){await page.goto('http://127.0.0.1:3100/?state=roles-owner',{waitUntil:'networkidle'});await captureMembershipCommands(page,name);}await page.goto('http://127.0.0.1:3100/?state=empty',{waitUntil:'networkidle'});if(name==='390x844'){const trigger=page.locator('.fcp-mobile-menu > summary');await trigger.click();await page.locator('.fcp-mobile-menu-body').getByRole('button',{name:'Выйти'}).waitFor({state:'visible'});await trigger.click();await page.mouse.move(0,height-1);await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());}await page.context().setOffline(true);await page.waitForTimeout(20);await page.screenshot({path:`${output}/offline-${name}.png`,fullPage:false});await page.context().setOffline(false);await page.close();}}finally{await browser.close();await new Promise((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));}

if(compareDirectory!==undefined){
  const pngNames=async(directory)=>(await readdir(directory)).filter((name)=>name.endsWith('.png')).sort();
  const actual=await pngNames(output);
  const expected=await pngNames(compareDirectory);
  if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`visual baseline file set differs: actual=${actual.join(',')} expected=${expected.join(',')}`);
  for(const name of actual){
    const [candidate,golden]=await Promise.all([readFile(join(output,name)),readFile(join(compareDirectory,name))]);
    const digest=(value)=>createHash('sha256').update(value).digest('hex');
    if(digest(candidate)!==digest(golden))throw new Error(`visual baseline mismatch: ${name}`);
  }
  console.log(`visual baseline compare passed: ${actual.length} PNGs`);
}
