import {defaultAgentRoutingPolicy,defaultProjectProcessPolicy} from '@fai-control-plane/domain';
import {Dashboard,Process,Shell,Tasks,type ProcessProject} from '../../src/mvp/phase-a-ui.tsx';

export type Pr2FixtureState='login'|'overview'|'tasks'|'tasks-detail'|'tasks-unknown'|'tasks-stale'|'tasks-empty'|'process'|'process-configured'|'process-unconfigured'|'process-read-only'|'process-stale'|'process-unavailable'|'process-configuring'|'process-awaiting-architecture';
const observedAt='2026-08-31T08:42:00.000Z';
const task=(suffix:string,title:string,statusOptionName:string,overrides:Record<string,unknown>={})=>({itemId:`item-${suffix}`,projectId:'project-ascon',issueId:suffix,title,url:`https://github.com/VF78/ascon/issues/${suffix}`,version:'fixture',statusOptionId:`status-${statusOptionName}`,statusOptionName,ownerOptionId:null,blocked:false,targetDate:'2026-09-04',parentIssueId:null,subIssueIds:[],dependencyIssueIds:[],assigneeIds:['user-vladimir'],assignees:[{id:'user-vladimir',login:'vfil',name:'Владимир'}],observedAt,...overrides});
const project=(name:string,slug:string,overrides:Record<string,unknown>={})=>({id:`project-${slug}`,workspaceId:'workspace-fixture',slug,name,repositoryUrl:`https://github.com/VF78/${slug}`,tracker:{provider:'github',configured:true,sourceUrl:`https://github.com/users/VF78/projects/${slug==='ascon'?'1':'2'}`,observedAt,freshness:'fresh',errorCode:null},tasks:slug==='ascon'?[task('41','Согласовать интерфейс задач','Ready'),task('42','Собрать TaskBoard','In Dev',{dependencyIssueIds:['dependency-1'],targetDate:'2026-09-02'}),task('43','Проверить адаптивность','QA',{blocked:true,targetDate:'2026-09-01'}),task('44','Принять foundation','Done',{targetDate:null})]:[task('45','Подготовить доступы','Backlog',{projectId:`project-${slug}`,targetDate:null})],...overrides});
const projects=[project('ASCON','ascon',{usage:{combinedTotal:9084200,taskTotals:{'item-41':0,'item-42':7844132,'item-43':720068}}}),project('MSA','msa')];
const process=(item:typeof projects[number],options:Readonly<{mode?:'manual'|'autonomous';configured?:boolean;canManage?:boolean;codexReady?:boolean;profileStatus?:ProcessProject['agentProfile']['status'];contextCurrent?:boolean}>={}):ProcessProject=>{const profileStatus=options.profileStatus??'ready';return {project:item as ProcessProject['project'],processPolicy:options.configured===false?null:{id:`policy-${item.id}`,projectId:item.id,version:'fixture',provenance:'fixture',createdAt:observedAt,policy:defaultProjectProcessPolicy},executionMode:{mode:options.mode??'manual',actorId:'fixture',changedAt:observedAt},routing:{policy:defaultAgentRoutingPolicy,executorCatalog:{'codex-cli':{available:options.codexReady??true,models:['gpt-5.6-terra','gpt-5.6-sol','gpt-6-astra','gpt-5.6-luna']}}},agentProfile:{status:profileStatus,profile:'fixture-profile',endpointPath:'/v1/runs',version:'fixture',documentFingerprint:'a'.repeat(64),contextSha:'b'.repeat(64)},contextCurrent:options.contextCurrent??profileStatus==='ready',canManageRouting:options.canManage??false,canManageContext:options.canManage??false};};

function Login(){return <main className="fcp-login"><section><span className="fcp-eyebrow">f(AI) Control</span><h1>Вход оператора</h1><p>Авторизация выполняется через GitHub.</p><a className="fcp-primary" href="/api/auth/github/login">Войти через GitHub</a></section></main>;}

export function Pr2Fixture({state}:Readonly<{state:Pr2FixtureState}>){if(state==='login')return <Login/>;const stale=state==='tasks-stale';const selected=state==='tasks-unknown'?project('ASCON','ascon'):stale?project('ASCON','ascon',{tracker:{provider:'github',configured:true,sourceUrl:'https://github.com/users/VF78/projects/1',observedAt,freshness:'stale',errorCode:null}}):projects[0]!;const items=state==='tasks-empty'?[project('ASCON','ascon',{tasks:[]})]:[selected,projects[1]!];const processView=state.startsWith('process');const view=state==='overview'?'dashboard':processView?'process':'tasks';const processStatus=state==='process-stale'?{profileStatus:'ready' as const,contextCurrent:false}:state==='process-unavailable'?{profileStatus:'error' as const}:state==='process-configuring'?{profileStatus:'configuring' as const}:state==='process-awaiting-architecture'?{profileStatus:'awaiting_architecture' as const}:{};const processProjects=!processView?[]:state==='process-unconfigured'?[process(items[0]!,{configured:false,canManage:true,codexReady:false}),process(items[1]!,{mode:'autonomous',canManage:true})]:state==='process-read-only'?[process(items[0]!),process(items[1]!,{mode:'autonomous'})]:[process(items[0]!,{canManage:true,...processStatus}),process(items[1]!,{mode:'autonomous',canManage:true})];return <Shell view={view} projects={items as ProcessProject['project'][]} operatorName="Владимир Филатов">{state==='overview'?<Dashboard projects={items as ProcessProject['project'][]}/>:processView?<Process projects={processProjects}/>:<Tasks projects={items as ProcessProject['project'][]} project={items[0] as ProcessProject['project']} task={state==='tasks-detail'?'item-42':undefined} filter={undefined}/>}</Shell>;}
