import {defaultAgentRoutingPolicy,defaultProjectProcessPolicy} from '@fai-control-plane/domain';
import {Dashboard,Process,Shell,Tasks,type ProcessProject} from '../../src/mvp/phase-a-ui.tsx';

export type Pr2FixtureState='login'|'overview'|'tasks'|'tasks-stale'|'tasks-empty'|'process';
const observedAt='2026-08-31T08:42:00.000Z';
const task=(suffix:string,title:string,statusOptionName:string,overrides:Record<string,unknown>={})=>({itemId:`item-${suffix}`,projectId:'project-ascon',issueId:suffix,title,url:`https://github.com/VF78/ascon/issues/${suffix}`,version:'fixture',statusOptionId:`status-${statusOptionName}`,statusOptionName,ownerOptionId:null,blocked:false,targetDate:'2026-09-04',parentIssueId:null,subIssueIds:[],dependencyIssueIds:[],assigneeIds:['user-vladimir'],assignees:[{id:'user-vladimir',login:'vfil',name:'Владимир'}],observedAt,...overrides});
const project=(name:string,slug:string,overrides:Record<string,unknown>={})=>({id:`project-${slug}`,workspaceId:'workspace-fixture',slug,name,repositoryUrl:`https://github.com/VF78/${slug}`,tracker:{provider:'github',configured:true,sourceUrl:`https://github.com/users/VF78/projects/${slug==='ascon'?'1':'2'}`,observedAt,freshness:'fresh',errorCode:null},tasks:slug==='ascon'?[task('41','Согласовать интерфейс задач','Ready'),task('42','Собрать TaskBoard','In Dev',{dependencyIssueIds:['dependency-1'],targetDate:'2026-09-02'}),task('43','Проверить адаптивность','QA',{blocked:true,targetDate:'2026-09-01'}),task('44','Принять foundation','Done',{targetDate:null})]:[task('45','Подготовить доступы','Backlog',{projectId:`project-${slug}`,targetDate:null})],...overrides});
const projects=[project('ASCON','ascon'),project('MSA','msa')];
const process=(item:typeof projects[number],mode:'manual'|'autonomous'='manual'):ProcessProject=>({project:item as ProcessProject['project'],processPolicy:{id:`policy-${item.id}`,projectId:item.id,version:'fixture',provenance:'fixture',createdAt:observedAt,policy:defaultProjectProcessPolicy},executionMode:{mode,actorId:'fixture',changedAt:observedAt},routing:{policy:defaultAgentRoutingPolicy,executorCatalog:{'codex-cli':{available:true,models:['gpt-5.6-terra','gpt-5.6-sol']}}},context:null,canManageRouting:false,canManageContext:false});

function Login(){return <main className="fcp-login"><section><span className="fcp-eyebrow">f(AI) Control</span><h1>Вход оператора</h1><p>Авторизация выполняется через GitHub.</p><a className="fcp-primary" href="/api/auth/github/login">Войти через GitHub</a></section></main>;}

export function Pr2Fixture({state}:Readonly<{state:Pr2FixtureState}>){if(state==='login')return <Login/>;const stale=state==='tasks-stale';const selected=stale?project('ASCON','ascon',{tracker:{provider:'github',configured:true,sourceUrl:'https://github.com/users/VF78/projects/1',observedAt,freshness:'stale',errorCode:null}}):projects[0]!;const items=state==='tasks-empty'?[project('ASCON','ascon',{tasks:[]})]:[selected,projects[1]!];const view=state==='overview'?'dashboard':state==='process'?'process':'tasks';return <Shell view={view} projects={items as ProcessProject['project'][]} operatorName="Владимир Филатов">{state==='overview'?<Dashboard projects={items as ProcessProject['project'][]}/>:state==='process'?<Process projects={[process(items[0]!),process(items[1]!,'autonomous')]}/>:<Tasks projects={items as ProcessProject['project'][]} project={items[0] as ProcessProject['project']} task={undefined} filter={undefined}/>}</Shell>;}
