import {Shell} from '../../src/mvp/phase-a-ui.tsx';
import {PhaseB,type PhaseBProject} from '../../src/mvp/phase-b-ui.tsx';

export type Pr3FixtureState='chats-configured'|'chats-unconfigured'|'chats-read-only'|'systems-configured'|'systems-unconfigured'|'systems-installing'|'systems-auth-required'|'systems-offline'|'systems-degraded'|'roles-owner'|'roles-read-only'|'roles-empty'|'empty';
const actorId='00000000-0000-4000-8000-000000000001';
const observedAt='2026-08-31T08:42:00.000Z';

function item(name:string,slug:string,configured:boolean,owner=true,system:'ready'|'installing'|'auth_required'|'error'|'degraded'|null=null):PhaseBProject { const id=`00000000-0000-4000-8000-${slug==='ascon'?'000000000010':'000000000020'}`;const runtime=system==='degraded'?'ready':system;return {project:{id,workspaceId:'00000000-0000-4000-000000000099',slug,name,repositoryUrl:`https://github.com/VF78/${slug}`,tracker:{provider:'github',configured:true,sourceUrl:`https://github.com/users/VF78/projects/${slug==='ascon'?'1':'2'}`,observedAt,freshness:'fresh',errorCode:null},tasks:[]},evidence:{projectId:id,people:[{membershipId:`member-${slug}-owner`,actorId,displayName:'Владимир Филатов',kind:'human',role:owner?'project_owner':'contributor',active:true,identityBindings:configured?[{provider:'telegram'}]:[]},{membershipId:`member-${slug}-hermes`,actorId:`00000000-0000-4000-8000-00000000000${slug==='ascon'?'2':'3'}`,displayName:'Hermes',kind:'agent',role:'contributor',active:true,identityBindings:[]}],ingress:[],conversations:[],messenger:{pending:0,delivered:0,failed:0,lastOccurredAt:null},agentSubmissions:{count:0,lastOccurredAt:null,recent:[]},receipts:[],audit:[]},sources:[],config:{hermes:configured,channels:{internal:{provider:configured?'telegram':null,configured,allowedUsers:configured?1:0,status:configured?'ready':null},client:{provider:configured?'element':null,configured,allowedUsers:0,status:configured?'interactive':null}}},agentProfile:system==='degraded'?{status:'error'}:null,runtimeSetup:runtime===null?null:{status:runtime},trackerCapabilities:null,trackerPreparation:null,wizardProgress:null} as unknown as PhaseBProject; }

export function Pr3Fixture({state}:Readonly<{state:Pr3FixtureState}>){const configured=state==='chats-configured'||state==='systems-configured';const readonly=state==='roles-read-only'||state==='chats-read-only';const system=state==='systems-installing'?'installing':state==='systems-auth-required'?'auth_required':state==='systems-offline'?'error':state==='systems-degraded'?'degraded':state==='systems-configured'?'ready':null;const initialProjects=state==='empty'?[]:[item('ASCON','ascon',configured,!readonly,system),item('MSA','msa',true,true,'ready')];const projects=state==='roles-empty'?[{...item('ASCON','ascon',false,true,null),evidence:{...item('ASCON','ascon',false,true,null).evidence!,people:[]}}]:initialProjects;const view=state.startsWith('chats')?'conversations':state.startsWith('systems')?'systems':'people';const workspacePeople=state==='roles-owner'?[{actorId:'00000000-0000-4000-8000-000000000050',displayName:'Екатерина Воронова'}]:[];return <Shell view={view} projects={projects.map(({project})=>project)} operatorName="Владимир Филатов"><PhaseB view={view} projects={projects} actorId={actorId} setup={undefined} workspacePeople={workspacePeople}/></Shell>;}
