import {createHash} from 'node:crypto';
import {useEffect,useState} from 'react';
import {Shell} from '../../src/mvp/phase-a-ui.tsx';
import {PhaseB,type PhaseBProject} from '../../src/mvp/phase-b-ui.tsx';
import {AsyncButton,CommandNoticeView} from '../../src/mvp/async-command.tsx';
import {projectActiveDocuments} from '../../src/mvp/project-setup-state.ts';

export type ProjectsFixtureState='zero'|'one'|'two'|'loading'|'error'|'partial'|'complete'|'integration-error'|'documents-empty'|'documents-loaded'|'documents-history'|'documents-missing-requirements'|'documents-read-only'|'setup-process'|'setup-team'|'setup-auto-advance'|'agent-connected'|'agent-offline'|'agent-degraded'|'read-only'|'command-pending'|'command-success'|'command-error';
const actorId='00000000-0000-4000-8000-000000000001';
const owner=(role='project_owner')=>({projectId:'',people:[{membershipId:'membership-1',actorId,displayName:'Владимир Филатов',kind:'human' as const,role,active:true,identityBindings:[]},{membershipId:'membership-2',actorId:'00000000-0000-4000-8000-000000000002',displayName:'Hermes',kind:'agent' as const,role:'contributor',active:true,identityBindings:[]}],ingress:[],conversations:[],messenger:{pending:0,delivered:0,failed:0,lastOccurredAt:null},agentSubmissions:{count:0,lastOccurredAt:null,recent:[]},receipts:[],audit:[]});
const source=(projectId:string,kind:string,name:string,index:number)=>({id:`00000000-0000-4000-8000-${String(index).padStart(12,'0')}`,projectId,kind:`project_document_v1:${kind}`,name,mediaType:'application/pdf',sha256:String(index).repeat(64).slice(0,64),sizeBytes:482_304+index*1024,sourceUrl:null,provenance:'fixture',createdAt:'2026-08-31T08:20:00.000Z'});
const fingerprint=(sources:readonly ReturnType<typeof source>[])=>createHash('sha256').update(projectActiveDocuments(sources).activeDocuments.slice().sort((left,right)=>left.kind.localeCompare(right.kind)||left.sha256.localeCompare(right.sha256)).map(({kind,sha256})=>`${kind}:${sha256}`).join('\n')).digest('hex');
function project(name:string,slug:string,mode:'partial'|'complete'|'integration-error'|'documents-empty'|'documents-loaded'|'documents-history'|'documents-missing-requirements'|'agent-connected'|'agent-offline'|'agent-degraded'|'read-only'='partial'):PhaseBProject{const id=`00000000-0000-4000-8000-${slug==='ascon'?'000000000010':'000000000020'}`;const loaded=!['partial','documents-empty'].includes(mode);const sources=mode==='documents-history'?[source(id,'passport','Паспорт проекта.pdf',1),source(id,'requirements','Техническое задание · актуальное.pdf',9),source(id,'requirements','Техническое задание · архив.pdf',2),source(id,'supplemental','Приложение A.pdf',3),source(id,'supplemental','Приложение B.pdf',4)]:mode==='documents-missing-requirements'?[source(id,'passport','Паспорт проекта.pdf',1),source(id,'architecture','Архитектура.pdf',2),source(id,'supplemental','Приложение.pdf',3)]:loaded?[source(id,'passport','Паспорт проекта.pdf',1),source(id,'requirements','Техническое задание.pdf',2)]:[];const complete=['complete','agent-connected'].includes(mode);const runtimeStatus=mode==='agent-offline'?'error':loaded||complete?'ready':'not_configured';const profileStatus=mode==='agent-degraded'?'error':loaded||complete?'ready':'not_configured';const evidence=owner(mode==='read-only'?'contributor':'project_owner');return {project:{id,workspaceId:'00000000-0000-4000-8000-000000000099',slug,name,repositoryUrl:`https://github.com/VF78/${slug}`,tracker:{provider:'github',configured:true,sourceUrl:`https://github.com/users/VF78/projects/${slug==='ascon'?'1':'2'}`,observedAt:'2026-08-31T08:42:00.000Z',freshness:mode==='integration-error'?'error':'fresh',errorCode:mode==='integration-error'?'fixture':null},tasks:[]},evidence:{...evidence,projectId:id},sources,config:{hermes:runtimeStatus==='ready',telegram:{configured:complete,allowedUsers:2},bitrix:{configured:false,clientActionsEnabled:false}},agentProfile:{status:profileStatus,profile:profileStatus==='ready'?'hermes-ascon':null,endpointPath:null,version:null,documentFingerprint:profileStatus==='ready'?fingerprint(sources):null},runtimeSetup:{status:runtimeStatus,telegramConfigured:complete,auth:null,failure:runtimeStatus==='error'?{code:'offline',message:'fixture'}:null},trackerCapabilities:{provider:'github',agentOwnerOptionId:'owner-hermes',doneStatusOptionId:'done',defaultBranch:'main'},trackerPreparation:{status:complete||loaded?'ready':mode==='integration-error'?'blocked':'not_started',version:null,runId:null,remainingDelta:[],approval:null,blocker:mode==='integration-error'?'GitHub не подтвердил состояние Project.':null},wizardProgress:{processConfirmed:complete||loaded,teamSkipped:complete,communicationsSkipped:complete}} as unknown as PhaseBProject;}
function CommandFixture({state}:Readonly<{state:'pending'|'success'|'error'}>){return <section className="fcp-project-detail-section" aria-label="Состояние команды"><header><h2>Проверка команды</h2><p>Детерминированное состояние общего асинхронного контракта.</p></header><AsyncButton pending={state==='pending'} pendingLabel="Сохраняем…">Сохранить</AsyncButton><CommandNoticeView notice={state==='success'?{tone:'success',text:'Изменение сохранено.'}:state==='error'?{tone:'error',text:'Не удалось выполнить действие. Данные не изменены.'}:null}/></section>;}
export function ProjectsFixture({state}:Readonly<{state:ProjectsFixtureState}>){const [autoAdvanced,setAutoAdvanced]=useState(false);useEffect(()=>{const advance=()=>setAutoAdvanced(true);window.addEventListener('fcp-fixture-refresh',advance);return()=>window.removeEventListener('fcp-fixture-refresh',advance);},[]);const setupFlow=state==='setup-process'||state==='setup-team'||state==='setup-auto-advance';const setupProcess=state==='setup-process'||(state==='setup-auto-advance'&&!autoAdvanced);const base=project('ASCON','ascon',state==='read-only'||state==='documents-read-only'?'read-only':state==='integration-error'?'integration-error':state==='documents-empty'?'documents-empty':state==='documents-loaded'||setupFlow?'documents-loaded':state==='documents-history'?'documents-history':state==='documents-missing-requirements'?'documents-missing-requirements':state==='agent-connected'?'agent-connected':state==='agent-offline'?'agent-offline':state==='agent-degraded'?'agent-degraded':state==='complete'||state.startsWith('command-')?'complete':'partial');const setupBase=setupFlow?{...base,evidence:{...base.evidence!,people:base.evidence!.people.slice(0,1)}}:base;const first=setupProcess?{...setupBase,wizardProgress:{...setupBase.wizardProgress!,processConfirmed:false}}:setupBase;const second=project('MSA','msa','complete');const projects=state==='zero'?[]:state==='one'?[first]:[first,second];const detail=!['zero','one','two','loading','error'].includes(state);return <Shell view="settings" projects={projects.map(({project})=>project)} operatorName="Владимир Филатов"><PhaseB view="settings" projects={projects} actorId={actorId} setup={detail?'ascon':undefined} workspacePeople={[]} projectsState={state==='loading'?'loading':state==='error'?'error':'ready'}/>{state.startsWith('command-')?<CommandFixture state={state.slice('command-'.length) as 'pending'|'success'|'error'}/>:null}</Shell>;}
