import {listApprovalEvidenceViews, listProjectOperatorEvidenceViews, listProjectSourceViews, listProjectTaskViews, type ProjectOperatorEvidenceView, type ProjectSourceView, type ProjectTaskView} from '@fai-control-plane/db';
import {Dashboard, Process, Shell, Tasks} from '../src/mvp/phase-a-ui.tsx';
import {AccessControls, ApprovalControl, SourceAddControl} from '../src/mvp/operator-controls.tsx';
import {AgentSubmitControl} from '../src/mvp/agent-submit-control.tsx';
import {integrationConfig, type IntegrationConfig} from '../src/mvp/integration-config.ts';
import {getDatabase, requireSession} from '../src/mvp/runtime.ts';

export const dynamic = 'force-dynamic';
type Area = 'dashboard'|'tasks'|'process'|'conversations'|'people'|'systems'|'settings';
type Query = Readonly<{view?: string; project?: string; task?: string; filter?: string}>;
const current = (view?: string): Area => ['dashboard','tasks','process','conversations','people','systems','settings'].includes(view ?? '') ? view as Area : 'dashboard';
const instant = (value: string) => new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}).format(new Date(value));
const evidenceFor = (project: ProjectTaskView|null, rows: readonly ProjectOperatorEvidenceView[]) => project === null ? null : rows.find((row) => row.projectId === project.id) ?? null;
const deliveryLabel = (value: {pending:number;delivered:number;failed:number}) => value.failed > 0 ? `Ошибка · ${value.failed}` : value.pending > 0 ? `Ожидает · ${value.pending}` : value.delivered > 0 ? `Доставлено · ${value.delivered}` : 'Нет данных';

function PageTitle({title,detail,state}:Readonly<{title:string;detail:string;state:string}>) { return <div className="fcp-page-title"><div><h1>{title}</h1><p>{detail}</p></div><span className="fcp-page-state">{state}</span></div>; }
function Empty({title}:Readonly<{title:string}>) { return <section className="fcp-blank"><div><h2>{title}</h2><p>После подключения данные появятся здесь.</p></div></section>; }
function Evidence({title,rows}:Readonly<{title:string;rows:readonly Readonly<{id:string;title:string;detail:string;at:string;url?:string}>[]}>) { return <section className="fcp-list-section fcp-evidence"><header><h2>{title}</h2></header>{rows.length===0?<p className="fcp-empty">Нет подтверждённых записей.</p>:<div className="fcp-record-list">{rows.map((row)=><article key={row.id}><div><strong>{row.title}</strong><small>{row.detail}</small></div><div><span>{instant(row.at)}</span>{row.url?<a href={row.url}>Открыть ↗</a>:null}</div></article>)}</div>}</section>; }
function Conversations({project,evidence,config}:Readonly<{project:ProjectTaskView|null;evidence:ProjectOperatorEvidenceView|null;config:IntegrationConfig}>) {
  if(!project)return <Empty title="Нет доступных проектов"/>;
  const contour = (input: Readonly<{name:string;provider:'telegram'|'bitrix24';contour:'trusted-main'|'client-edge';configured:boolean;note:string}>) => {
    const action=evidence?.conversations.find((item)=>item.contour===input.contour);
    const bindings=evidence?.people.filter((person)=>person.identityBindings.some((identity)=>identity.provider===input.provider))??[];
    const confirmed=action!==undefined;
    return <article className="fcp-contour" key={input.provider}><header><div><span>{input.name}</span><h2>{input.provider==='telegram'?'Внутренний Telegram':'Внешний Bitrix24'}</h2></div><b className={confirmed?'ready':input.configured?'neutral':'danger'}>{confirmed?'Есть подтверждённая активность':input.configured?'Настроено':'Не настроено'}</b></header><dl><div><dt>Конфигурация</dt><dd>{input.configured?'Secret references и binding заданы':'Требуется настройка composition'}</dd></div><div><dt>Доступ</dt><dd>{bindings.length===0?'Identity не привязаны':`${bindings.length} identity`}</dd></div><div><dt>Подтверждённые действия</dt><dd>{action===undefined?'Нет данных':`${action.count} · ${instant(action.lastOccurredAt)}`}</dd></div><div><dt>Уведомления</dt><dd>{input.contour==='trusted-main'?deliveryLabel(evidence?.messenger??{pending:0,delivered:0,failed:0}):'Не включены'}</dd></div></dl><p>{input.note}</p><small>Транскрипты, payload и секреты не хранятся и не отображаются.</small></article>;
  };
  return <><PageTitle title="Чаты" detail={`${project.name} · внутренний и клиентский контуры`} state="Без транскриптов"/><section className="fcp-contour-grid">{contour({name:'Внутренний контур',provider:'telegram',contour:'trusted-main',configured:config.telegram.configured,note:`Разрешённые операторы: ${config.telegram.allowedUsers}. Действия проходят аутентификацию и policy.`})}{contour({name:'Клиентский контур',provider:'bitrix24',contour:'client-edge',configured:config.bitrix.configured&&config.bitrix.clientActionsEnabled,note:config.bitrix.clientActionsEnabled?'Клиентские действия разрешены явной policy; фактическая активность подтверждается только audit.':'Клиентские действия выключены policy; Bitrix-контур fail-closed.'})}</section></>;
}
function People({project,evidence,actorId}:Readonly<{project:ProjectTaskView|null;evidence:ProjectOperatorEvidenceView|null;actorId:string}>) { if(!project)return <Empty title="Нет доступных проектов"/>; const people=evidence?.people??[]; return <><PageTitle title="Роли и доступы" detail={`${project.name} · участники, роли и provider identity hashes`} state={`${people.filter((person)=>person.active).length} активных`}/><AccessControls projectId={project.id} canManage={people.some((person)=>person.actorId===actorId&&person.active&&person.role==='project_owner')} members={people}/><section className="fcp-list-section"><header><h2>Роли в проекте</h2><span>Изменение — только owner через canonical command</span></header>{people.length===0?<p className="fcp-empty">Нет данных о членствах.</p>:<div className="fcp-record-list">{people.map((person)=><article key={person.actorId}><div><span>{person.kind} · {person.role}</span><strong>{person.displayName}</strong><small>{person.identityBindings.length===0?'Внешние identity не привязаны':person.identityBindings.map((identity)=>`${identity.provider}: ${identity.subjectHash.slice(0,12)}…`).join(' · ')}</small></div><b className={`fcp-decision ${person.active?'approved':'rejected'}`}>{person.active?'active':'inactive'}</b></article>)}</div>}</section></>; }
function Systems({project,evidence,sources,config}:Readonly<{project:ProjectTaskView|null;evidence:ProjectOperatorEvidenceView|null;sources:readonly ProjectSourceView[];config:IntegrationConfig}>) { if(!project)return <Empty title="Нет доступных проектов"/>; const submissions=evidence?.agentSubmissions??{count:0,lastOccurredAt:null}; const rows=[...(evidence?.receipts??[]).map((item,index)=>({id:`receipt-${index}`,title:item.commandType,detail:item.resultReference,at:item.occurredAt})),...(evidence?.audit??[]).map((item,index)=>({id:`audit-${index}`,title:item.action,detail:item.targetReference,at:item.occurredAt}))]; return <><PageTitle title="Агенты и системы" detail={`${project.name} · наблюдение интеграций, receipts и audit`} state="Явная команда"/><section className="fcp-agent-command"><header><div><span className="fcp-eyebrow">ASCON Hermes</span><h2>Только явная команда оператора</h2><p>Автоматического запуска backlog нет. Браузерная команда требует активной операторской сессии, same-origin проверку и точный свежий факт GitHub Project.</p></div><b className={config.hermes?'ready':'danger'}>{config.hermes?'Настроено':'Не настроено'}</b></header><dl className="fcp-system-facts"><div><dt>Integration readiness</dt><dd>{config.hermes?'Endpoint и secret reference заданы':'Требуется настройка composition'}</dd></div><div><dt>Явные запуски</dt><dd>{submissions.count}</dd></div><div><dt>Последний receipt</dt><dd>{submissions.lastOccurredAt===null?'Нет данных':instant(submissions.lastOccurredAt)}</dd></div></dl></section><AgentSubmitControl projectId={project.id} tasks={project.tasks} sources={sources.filter((source)=>source.projectId===project.id)}/><Evidence title="Receipts и audit" rows={rows}/></>; }
function Settings({project,sources}:Readonly<{project:ProjectTaskView|null;sources:readonly ProjectSourceView[]}>) { if(!project)return <Empty title="Нет доступных проектов"/>; const rows=sources.filter((source)=>source.projectId===project.id); return <><PageTitle title="План и подключения" detail={`${project.name} · источники Control Plane`} state={`${rows.length} записей`}/><SourceAddControl projectId={project.id}/><section className="fcp-list-section"><header><h2>Подтверждённые источники</h2></header>{rows.length===0?<p className="fcp-empty">Источники ещё не добавлены.</p>:<div className="fcp-record-list">{rows.map((source)=><article key={source.id}><div><span>{source.kind} · {source.mediaType}</span><strong>{source.name}</strong><small>{source.provenance} · {source.sha256.slice(0,12)}…</small></div>{source.sourceUrl===null?null:<a href={source.sourceUrl}>Источник ↗</a>}</article>)}</div>}</section></>; }
export default async function Home({searchParams}:Readonly<{searchParams:Promise<Query>}>) { let session:Awaited<ReturnType<typeof requireSession>>|null=null; try {session=await requireSession();} catch {session=null;} if(!session)return <main className="fcp-login"><section><span className="fcp-eyebrow">f(AI) Control</span><h1>Вход оператора</h1><p>Авторизация выполняется через GitHub.</p><a className="fcp-primary" href="/api/auth/github/login">Войти через GitHub</a></section></main>; const query=await searchParams; const view=current(query.view); const database=getDatabase(); const [projects,sources,approvals,evidence]=await Promise.all([listProjectTaskViews(database,session.actorId),listProjectSourceViews(database,session.actorId),listApprovalEvidenceViews(database,session.actorId),listProjectOperatorEvidenceViews(database,session.actorId)]); const selected=projects.find((project)=>project.slug===query.project)??projects[0]??null; const operatorEvidence=evidenceFor(selected,evidence); const config=integrationConfig(); const content=view==='tasks'?<Tasks project={selected} task={query.task} filter={query.filter} approvalControl={(taskId) => selected === null ? null : <><ApprovalControl projectId={selected.id} taskId={taskId}/><Evidence title="Зафиксированные согласования" rows={approvals.filter((approval)=>approval.projectId===selected.id&&approval.targetReference===taskId).map((approval)=>({id:approval.id,title:approval.decision==='approved'?'Согласовано':'Отклонено',detail:`${approval.kind} · ${approval.targetVersion}`,at:approval.decidedAt,url:approval.targetUrl}))}/></>}/>:view==='process'?<Process project={selected}/>:view==='conversations'?<Conversations project={selected} evidence={operatorEvidence} config={config}/>:view==='people'?<People project={selected} evidence={operatorEvidence} actorId={session.actorId}/>:view==='systems'?<Systems project={selected} evidence={operatorEvidence} sources={sources} config={config}/>:view==='settings'?<Settings project={selected} sources={sources}/>:<Dashboard projects={projects}/>; return <Shell view={view} projects={projects} selected={selected} operatorName={session.displayName}>{content}</Shell>; }
