import {readFile} from 'node:fs/promises';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it,vi} from 'vitest';
import {ProjectsFixture,type ProjectsFixtureState} from '../../tests/visual/projects-setup-fixtures.tsx';
import {Pr3Fixture,type Pr3FixtureState} from '../../tests/visual/pr3-fixtures.tsx';

vi.mock('next/navigation',()=>({useRouter:()=>({refresh:vi.fn(),push:vi.fn(),replace:vi.fn()})}));

const source=async(name:string)=>readFile(new URL(`./${name}`,import.meta.url),'utf8');

describe('Projects portfolio and setup vertical slice',()=>{
  it('keeps Chats scan-first and reveals Telegram configuration only through an owner-scoped dialog',async()=>{const [view,controls]=await Promise.all([source('phase-b-ui.tsx'),source('operator-controls.tsx')]);const configured=renderToStaticMarkup(<Pr3Fixture state="chats-configured"/>);const unconfigured=renderToStaticMarkup(<Pr3Fixture state="chats-unconfigured"/>);const readonly=renderToStaticMarkup(<Pr3Fixture state="chats-read-only"/>);expect(view).toContain('<TelegramSettingsDialogControl projectId={project.id} projectName={project.name}/>');expect(view).not.toContain('<TelegramSettingsControl projectId={project.id}/>');expect(unconfigured).toContain('aria-label="Настроить Telegram: ASCON"');expect(unconfigured).not.toContain('Токен бота');expect(configured).not.toContain('Настроить Telegram');expect(readonly).toContain('Доступ только для просмотра');expect(readonly).not.toContain('Настроить Telegram: ASCON');expect(controls).toContain('function TelegramSettingsForm');expect(controls).toContain('TelegramSettingsDialogControl');expect(controls).toContain('if(!command.pending)setOpen(false);');expect(controls).toContain('composition="dialog" command={command}');expect(controls.match(/action:\'connect_messenger\'/g)).toHaveLength(1);expect(controls).toContain('`/api/projects/${projectId}/runtime`');expect(controls).toContain('idempotencyKey:`project-messenger:${id()}`');});

  it('shares the scan-first membership manager between Roles and project setup',async()=>{const [view,wizard,controls]=await Promise.all([source('phase-b-ui.tsx'),source('project-wizard.tsx'),source('operator-controls.tsx')]);expect(view).toContain('<ProjectMembershipManager');expect(wizard).toContain('<ProjectMembershipManager');expect(wizard).not.toContain('<AccessControls');expect(controls).toContain('export function ProjectMembershipManager');expect(controls).not.toContain('export function AccessControls');expect(controls).not.toContain('function RoleButtons');expect(controls).toContain('Изменить членство: ${member.displayName} · ${projectName}');expect(controls).toContain('Добавить участника: ${projectName}');expect(controls).toContain('title="Добавить участника"');expect(controls).toContain('Выберите сотрудника');expect(controls).toContain('Изменения применяются только к этому проекту.');expect(controls).toContain("post(`/api/access/memberships/${member.membershipId}`,{role,active:true})");expect(controls).toContain("post('/api/access/onboarding'");expect(controls).toContain('<Dialog open={open}');});

  it('renders deterministic owner, read-only and empty Roles fixtures without a mutation panel',()=>{const states:Pr3FixtureState[]=['roles-owner','roles-read-only','roles-empty'];for(const state of states)expect(renderToStaticMarkup(<Pr3Fixture state={state}/>),state).toContain('Роли и доступы');const owner=renderToStaticMarkup(<Pr3Fixture state="roles-owner"/>);const readonly=renderToStaticMarkup(<Pr3Fixture state="roles-read-only"/>);const empty=renderToStaticMarkup(<Pr3Fixture state="roles-empty"/>);expect(owner.match(/class="fcp-secondary fcp-c-membership-add"/g)).toHaveLength(2);expect(owner.match(/Изменить членство/g)).toHaveLength(4);expect(readonly).toContain('Доступ только для просмотра');expect(readonly.match(/class="fcp-secondary fcp-c-membership-add"/g)).toHaveLength(1);expect(readonly.match(/Изменить членство/g)).toHaveLength(2);expect(empty).toContain('Участники ещё не добавлены.');expect(empty).not.toContain('Добавить участника');expect(empty).toContain('Доступ только для просмотра');});

  it('renders every deterministic portfolio/setup state without a separate production route',()=>{const states:ProjectsFixtureState[]=['zero','one','two','loading','error','partial','complete','integration-error','documents-empty','documents-loaded','documents-history','documents-missing-requirements','agent-connected','agent-offline','agent-degraded','read-only','command-pending','command-success','command-error'];for(const state of states){const html=renderToStaticMarkup(<ProjectsFixture state={state}/>);expect(html,`fixture ${state}`).toContain('Проекты');expect(html,`fixture ${state}`).not.toContain('Настройки проектов');}});

  it('renders compact zero/one/two portfolios with one primary Add action',()=>{const zero=renderToStaticMarkup(<ProjectsFixture state="zero"/>);const one=renderToStaticMarkup(<ProjectsFixture state="one"/>);const two=renderToStaticMarkup(<ProjectsFixture state="two"/>);expect(zero.match(/Добавить проект/g)).toHaveLength(1);expect(one.match(/<article class="fcp-c-project-row">/g)).toHaveLength(1);expect(two.match(/<article class="fcp-c-project-row">/g)).toHaveLength(2);expect(two).toContain('Настройка 2/5');expect(two).toContain('Настройка 5/5');});

  it('keeps incomplete setup in one rail-selected current step without tabs or duplicate CTA',()=>{const partial=renderToStaticMarkup(<ProjectsFixture state="partial"/>);expect(partial).toContain('Настройка 2/5');expect(partial).toContain('aria-label="Готовность проекта"');expect(partial).not.toContain('role="tablist"');expect(partial).not.toContain('Продолжить настройку');expect(partial).toMatch(/class="is-active"[^>]*>.*?<b>Документы<\/b>/);expect(partial).toMatch(/<button[^>]*disabled=""[^>]*>4<b>Агент<\/b>/);expect(partial).toContain('Загрузить документы');expect(partial).not.toContain('Установить ИИ-агента');expect(partial).not.toContain('Настроить контекст');expect(partial).not.toContain('Поставить задачу Hermes');expect(partial).toContain('Удалить проект</button>');});

  it('renders management tabs only after setup, while retaining complete controls',()=>{const partial=renderToStaticMarkup(<ProjectsFixture state="partial"/>);const complete=renderToStaticMarkup(<ProjectsFixture state="complete"/>);const offline=renderToStaticMarkup(<ProjectsFixture state="agent-offline"/>);const readonly=renderToStaticMarkup(<ProjectsFixture state="read-only"/>);expect(partial).not.toContain('role="tablist"');for(const label of ['Обзор','Интеграции','Контекст','Агент','Доступ'])expect(complete).toContain(`>${label}</button>`);expect(complete).toContain('role="tablist"');expect(complete).not.toContain('aria-label="Готовность проекта"');expect(complete).toContain('Первая задача');expect(complete).toContain('Паспорт проекта.pdf');expect(offline).toContain('Требует проверки');expect(readonly).toContain('Доступ только для просмотра');expect(readonly).not.toContain('>Удалить проект</button>');});

  it('raises a canonical warning with the mandatory document category that is still missing',async()=>{const [missing,foundation]=[renderToStaticMarkup(<ProjectsFixture state="documents-missing-requirements"/>),await source('../ui/foundation.tsx')];expect(missing).toContain('class="fcp-c-inline-alert is-warning"');expect(missing).toContain('role="alert"');expect(missing).toContain('Не загружен обязательный документ: Техническое задание.');expect(missing).toContain('Архитектура.pdf');expect(missing).toContain('Приложение.pdf');expect(foundation).toContain('export function InlineAlert');});

  it('renders pending, success and error command states through the single async owner',()=>{const pending=renderToStaticMarkup(<ProjectsFixture state="command-pending"/>);const success=renderToStaticMarkup(<ProjectsFixture state="command-success"/>);const error=renderToStaticMarkup(<ProjectsFixture state="command-error"/>);expect(pending).toContain('aria-busy="true"');expect(pending).toContain('Сохраняем…');expect(success).toContain('Изменение сохранено.');expect(error).toContain('role="alert"');expect(error).toContain('Данные не изменены.');});

  it('keeps the settings route while presenting compact Projects rows',async()=>{const [view,navigation]=await Promise.all([source('phase-b-ui.tsx'),source('phase-a-ui.tsx')]);expect(navigation).toContain("settings:'Проекты'");expect(view).toContain('title="Проекты"');expect(view).toContain('<ProjectListRow');expect(view).toContain('Настройка ${grouped.complete}/5');expect(view).toContain('/?view=settings&setup=');expect(view).not.toContain('function SettingsProject');expect(view).not.toContain('ProjectDeleteControl');expect(view).not.toContain('ProjectDocumentsEditor');});

  it('shows deterministic empty, loading, error and invalid-slug recovery states',async()=>{const view=await source('phase-b-ui.tsx');expect(view).toContain("projectsState==='loading'?<Skeleton");expect(view).toContain("projectsState==='error'?<ErrorState");expect(view).toContain('title="Проектов пока нет"');expect(view).toContain('title="Проект не найден"');expect(view).toContain('Вернуться к проектам');});

  it('uses five accessible project tabs and the approved setup rail',async()=>{const [wizard,foundation]=await Promise.all([source('project-wizard.tsx'),source('../ui/foundation.tsx')]);for(const label of ['Обзор','Интеграции','Контекст','Агент','Доступ'])expect(wizard).toContain(`label:'${label}'`);for(const label of ['Репозиторий','Трекер','Документы','Агент','Проверка'])expect(wizard).toContain(`'${label}'`);expect(wizard).toContain('<SetupRail');expect(foundation).toContain('role="tablist"');expect(foundation).toContain("event.key==='ArrowRight'");expect(foundation).toContain("event.key==='Home'");expect(foundation).toContain('role="tabpanel"');});

  it('uses rail selection to reveal and focus the current step without scroll glue',async()=>{const wizard=await source('project-wizard.tsx');expect(wizard).toContain('const selectGroup=(id:string)=>');expect(wizard).toContain('setActiveStep(step);setNextTarget(step);');expect(wizard).toContain('data-setup-step-target={String(step)}');expect(wizard).toContain("target?.querySelector<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),a[href]')?.focus()");expect(wizard).not.toContain('scrollIntoView');expect(wizard).not.toContain('document.querySelector');});

  it('regroups every existing setup command without changing its endpoint or idempotency owner',async()=>{const wizard=await source('project-wizard.tsx');for(const command of ["action:'confirm_process'","action:'skip_team'","action:'skip_communications'","action:'install'","action:'confirm_and_start'","action:'create_and_start'"])expect(wizard).toContain(command);for(const seam of ['/wizard-progress','/runtime','/agent-profile','/tracker-preparation','/api/approvals/','/api/tasks/executor'])expect(wizard).toContain(seam);expect(wizard).toContain('<ProjectMembershipManager');expect(wizard).toContain('<TelegramSettingsControl');expect(wizard).toContain('<ProjectDocumentsEditor');expect(wizard).toContain('<FirstTask item={item}/>');});

  it('advances the visible step only after refreshed authoritative setup state changes',async()=>{const wizard=await source('project-wizard.tsx');expect(wizard).toContain('const setupVersion=`${item.project.id}:${setup.nextStep}:${setup.complete}`');expect(wizard).toContain('const observedSetupVersion=useRef(setupVersion)');expect(wizard).toContain('if(observedSetupVersion.current===setupVersion)return');expect(wizard).toContain('setActiveStep(setup.nextStep);setNextTarget(setup.nextStep)');expect(wizard).not.toContain('setupStepTabs');expect(wizard).not.toContain('setupRailTabs');});

  it('keeps one document upload path and gives only owners exact document actions',async()=>{const [wizard,control]=await Promise.all([source('project-wizard.tsx'),source('operator-controls.tsx')]);expect(wizard).toContain('documents.activeDocuments.map');expect(wizard).toContain('Скачать');expect(wizard).toContain('canManage?<ProjectDocumentDeleteControl');expect(control).toContain('Загрузить документы');expect(control).toContain('Добавить ещё файл');expect(control).toContain('aria-label={`Удалить документ: ${documentName}`}');expect(control).not.toContain('>Очистить<');expect(control).not.toContain('export function ProjectDocumentUploadControl');expect(control).toContain('upload_timeout');const owner=renderToStaticMarkup(<ProjectsFixture state="complete"/>);const member=renderToStaticMarkup(<ProjectsFixture state="read-only"/>);expect(owner).toContain('aria-label="Удалить документ: Паспорт проекта.pdf"');expect(member).not.toContain('aria-label="Удалить документ:');});

  it('warns about exact missing mandatory documents without rejecting a combined document',async()=>{const wizard=await source('project-wizard.tsx');expect(wizard).toContain("documents.categories.has('combined')?[]");expect(wizard).toContain('Не загружен${missingMandatoryDocuments.length===1');expect(wizard).toContain('<InlineAlert>');});

  it('renders all document types as one visible accessible choice group',async()=>{const empty=renderToStaticMarkup(<ProjectsFixture state="documents-empty"/>);for(const label of ['Паспорт проекта','Техническое задание','Архитектура','Прочее'])expect(empty).toContain(`>${label}</button>`);expect(empty).toContain('role="group" aria-label="Тип документа 1"');expect(empty).toContain('aria-pressed="true">Паспорт проекта</button>');for(const label of ['Техническое задание','Архитектура','Прочее'])expect(empty).toContain(`aria-pressed="false">${label}</button>`);expect(empty).not.toContain('<select');const control=await source('operator-controls.tsx');expect(control).toContain("onChange={(category)=>update(row.id,{category})}");});

  it('shows only the authoritative fixed document version while retaining supplemental documents',async()=>{const [wizard,state]=await Promise.all([source('project-wizard.tsx'),source('project-setup-state.ts')]);expect(wizard).toContain('projectActiveDocuments(projectSources)');expect(wizard).toContain('documents.activeDocuments.map');expect(state).toContain("else if(!activeFixed.has(category))activeFixed.set(category,document)");expect(state).toContain('activeSupplemental.push(document)');});

  it('keeps destructive action in one reusable Danger Zone with exact-name confirmation',async()=>{const [wizard,control,foundation]=await Promise.all([source('project-wizard.tsx'),source('operator-controls.tsx'),source('../ui/foundation.tsx')]);expect(wizard).toContain('const dangerZone=<DangerZone');expect(wizard.indexOf('const dangerZone')).toBeLessThan(wizard.indexOf('const accessPanel'));expect(wizard).toContain('</section>{dangerZone}</>}</div>');expect(control).toContain('confirmation!==projectName');expect(control).toContain('<Dialog open={confirming}');expect(control).toContain("router.replace('/?view=settings')");expect(control).not.toContain("window.location.assign('/?view=settings')");expect(foundation).toContain('role="dialog"');expect(foundation).toContain("event.key==='Escape'");expect(foundation).toContain("event.key!=='Tab'");});

  it('renders capability-aware read-only setup while retaining owner and operator actions',async()=>{const wizard=await source('project-wizard.tsx');expect(wizard).toContain("const canManage=role==='project_owner'");expect(wizard).toContain("const canStart=role==='project_owner'||role==='operator'");expect(wizard).toContain('<ReadOnlyNotice/>');expect(wizard).toContain('canManage?<ProjectDeleteControl');});

  it('loads existing projections once and per-project facts concurrently',async()=>{const page=await source('../../app/page.tsx');expect(page).toContain('listProjectOperatorEvidenceViews(database, session.actorId, evidenceSections)');expect(page).toContain('listProjectSourceViews(database, session.actorId)');expect(page).toContain('Promise.all(projects.map(async (project)');expect(page).toContain('<PhaseB view={view} projects={phaseBProjects}');});
});
