import type {ProjectContextStatusView, ProjectProcessPolicyView, ProjectTaskView} from '@fai-control-plane/db';
import type {AgentExecutorCatalog, AgentRoutingPolicy, AgentRoute} from '@fai-control-plane/domain';
import type {ReactNode} from 'react';
import {AlertTriangle, ArrowRight, Bot, ChevronRight, CircleDot, FileCheck2, FolderKanban, LayoutDashboard, ListChecks, Menu, MessageSquareText, Settings2, ShieldCheck, UsersRound, Workflow} from 'lucide-react';
import {dashboardProjection, phaseAStages, readableAssignees} from './phase-a-view.ts';
import {AgentRoutingControl, HermesContextControl, LogoutControl} from './operator-controls.tsx';

export type PhaseArea = 'dashboard'|'tasks'|'process'|'conversations'|'people'|'systems'|'settings';
const labels: Record<PhaseArea,string> = {dashboard:'Обзор',tasks:'Задачи',process:'Процесс',conversations:'Чаты',people:'Роли и доступы',systems:'Агенты и системы',settings:'План и подключения'};
const icons: Record<PhaseArea,typeof LayoutDashboard> = {dashboard:LayoutDashboard,tasks:ListChecks,process:Workflow,conversations:MessageSquareText,people:UsersRound,systems:Bot,settings:Settings2};
const work: readonly PhaseArea[] = ['dashboard','tasks','process','conversations'];
export const phaseHref = (view: PhaseArea, project?: string, task?: string, filter?: string) => { const query = new URLSearchParams({view}); if (project) query.set('project', project); if (task) query.set('task', task); if (filter) query.set('filter', filter); return `/?${query}`; };
const date = (value: string) => new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Moscow'}).format(new Date(`${value}T12:00:00.000Z`));
const freshness = (project: ProjectTaskView) => project.tracker.errorCode ? 'Данные требуют обновления' : project.tracker.observedAt === null ? 'Снимок не получен' : `${project.tracker.freshness === 'fresh' ? 'Обновлено' : 'Снимок устарел'} ${new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}).format(new Date(project.tracker.observedAt))}`;
const tone = (value: ProjectTaskView['tracker']['freshness']) => value === 'fresh' ? 'success' : value === 'stale' ? 'warning' : 'neutral';
const projectNoun = (count: number) => count % 10 === 1 && count % 100 !== 11 ? 'проект' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 10 || count % 100 >= 20) ? 'проекта' : 'проектов';
function Status({value,label}: Readonly<{value: ProjectTaskView['tracker']['freshness'];label?: string}>) { return <span className={`fcp-status ${tone(value)}`}><CircleDot aria-hidden="true" size={14}/>{label ?? (value === 'fresh' ? 'Свежий snapshot' : value === 'stale' ? 'Snapshot устарел' : 'Данные недоступны')}</span>; }
export function Shell({view,projects,selected,operatorName,children}: Readonly<{view:PhaseArea;projects:readonly ProjectTaskView[];selected:ProjectTaskView|null;operatorName:string;children:ReactNode}>) {
  const nav = (items: readonly PhaseArea[]) => items.map((item) => { const Icon = icons[item]; return <a href={phaseHref(item,selected?.slug)} aria-current={view === item ? 'page' : undefined} key={item}><span className="fcp-nav-icon"><Icon aria-hidden="true" size={17}/></span><span>{labels[item]}</span></a>; });
  return <div className="fcp-workspace"><div className="fcp-shell-layout"><aside className="fcp-sidebar"><a className="fcp-brand" href={phaseHref('dashboard')}><i aria-hidden="true">f</i><b>f(AI) Control</b></a><nav className="fcp-sidebar-section fcp-project-list-nav" aria-label="Доступные проекты"><span>Проекты</span>{projects.map((project) => <a href={phaseHref(view,project.slug)} aria-current={selected?.id === project.id ? 'page' : undefined} key={project.id}><i className="fcp-project-initial fcp-project-initial--ascon">{project.name[0]}</i><div><b>{project.name}</b><small>{freshness(project)}</small></div><CircleDot aria-label={`Состояние: ${project.tracker.freshness}`} className={`fcp-project-health ${tone(project.tracker.freshness)}`} size={13}/></a>)}</nav><nav className="fcp-sidebar-section fcp-sidebar-nav" aria-label="Рабочие разделы"><span>Работа</span>{nav(work)}</nav><nav className="fcp-sidebar-section fcp-sidebar-nav" aria-label="Контроль"><span>Контроль</span>{nav(['systems'])}</nav><nav className="fcp-sidebar-section fcp-sidebar-nav fcp-sidebar-settings" aria-label="Настройки"><span>Настройки</span>{nav(['settings','people'])}</nav></aside><header className="fcp-topbar"><a className="fcp-mobile-brand" href={phaseHref('dashboard')}>f(AI) Control</a><strong>{selected === null ? labels[view] : `${selected.name} · ${labels[view]}`}</strong><span className="fcp-access-count"><ShieldCheck aria-hidden="true" size={15}/>Доступ: {projects.length} {projectNoun(projects.length)}</span><span className="fcp-user-avatar" aria-label={`Оператор: ${operatorName}`}>{operatorName.split(/\s+/).map((part) => part[0]).join('').slice(0,2).toUpperCase()}</span><LogoutControl/><details className="fcp-mobile-menu"><summary aria-label="Открыть навигацию"><Menu aria-hidden="true" size={20}/></summary><div className="fcp-mobile-menu-body"><nav aria-label="Проекты"><span>Проекты</span>{projects.map((project) => <a href={phaseHref(view,project.slug)} key={project.id}><FolderKanban aria-hidden="true" size={16}/>{project.name}</a>)}</nav><nav aria-label="Работа"><span>Работа</span>{nav(work)}</nav><nav aria-label="Контроль"><span>Контроль</span>{nav(['systems'])}</nav><nav aria-label="Настройки"><span>Настройки</span>{nav(['settings','people'])}</nav><LogoutControl/></div></details></header><main className="fcp-main">{children}</main></div></div>;
}

function ProjectHeader({project,title,showTrackerState=true}: Readonly<{project:ProjectTaskView;title?:string;showTrackerState?:boolean}>) { return <><div className="fcp-crumbs"><a href={phaseHref('dashboard',project.slug)}>Проекты</a><ChevronRight aria-hidden="true" size={14}/><a href={phaseHref('dashboard',project.slug)}>{project.name}</a>{title === undefined ? null : <><ChevronRight aria-hidden="true" size={14}/><strong>{title}</strong></>}</div><div className="fcp-project-title"><div><h1>{title ?? project.name}</h1>{showTrackerState ? <span>GitHub · {freshness(project)}</span> : null}</div>{showTrackerState ? <Status value={project.tracker.freshness}/> : null}</div></>; }
function ContextTabs({items}: Readonly<{items:readonly Readonly<{label:string;href:string;active:boolean;count?:number;disabled?:boolean}>[]}>) { return <nav className="fcp-tabs fcp-context-tabs" aria-label="Разделы">{items.map((item) => <a href={item.href} aria-current={item.active ? 'page' : undefined} aria-disabled={item.disabled || undefined} title={item.disabled ? 'Недоступно: нет подтверждённого соответствия оператора и GitHub assignee' : undefined} key={item.label}>{item.label}{item.count === undefined ? null : <span>{item.count}</span>}</a>)}</nav>; }
function Empty({title}: Readonly<{title:string}>) { return <section className="fcp-blank"><div><h2>{title}</h2><p>После подключения данные появятся здесь.</p></div></section>; }

export function Dashboard({projects}: Readonly<{projects:readonly ProjectTaskView[]}>) { return <><div className="fcp-page-title"><div><h1>Обзор проектов</h1><p>Подтверждённый прогресс каждого доступного проекта — по количеству задач.</p></div></div><section className="fcp-dashboard-progress" aria-label="Прогресс доступных проектов">{projects.map((project) => { const progress = dashboardProjection(project.tasks); const width = (key: keyof typeof progress.states) => progress.total === 0 ? 0 : progress.states[key] / progress.total * 100; return <a className="fcp-dashboard-progress-card" href={phaseHref('dashboard',project.slug)} key={project.id}><header><div><span>{project.name}</span><small>GitHub Project</small></div><Status value={project.tracker.freshness}/></header>{project.tracker.observedAt === null ? <strong>Нет данных</strong> : <><strong>{progress.states.accepted} / {progress.total}</strong><div className="fcp-dashboard-progress-bar" aria-label="Прогресс по количеству задач"><span className="fcp-scope-accepted" style={{width:`${width('accepted')}%`}}/><span className="fcp-scope-review" style={{width:`${width('review')}%`}}/><span className="fcp-scope-in-progress" style={{width:`${width('in-progress')}%`}}/><span className="fcp-scope-not-started" style={{width:`${width('not-started')}%`}}/></div><ul>{([['accepted','Принято'],['review','На проверке'],['in-progress','В работе'],['not-started','Не начато']] as const).map(([key,label]) => <li className={`fcp-scope-${key}`} key={key}><span aria-hidden="true"/>{label} {progress.states[key]}</li>)}</ul></>}<dl className="fcp-dashboard-facts"><div><dt>Текущий этап</dt><dd>{progress.phase}</dd></div><div><dt>Ближайший срок</dt><dd>{progress.deadline === null ? 'Не задан' : date(progress.deadline)}</dd></div><div><dt>Риски</dt><dd>{progress.blocked === null ? 'Нет данных' : progress.blocked}</dd></div><div><dt>Главный риск</dt><dd>{progress.blocked !== null && progress.blocked > 0 ? 'Blocked в GitHub Project' : 'Нет открытых рисков'}</dd></div></dl>{progress.blocked !== null && progress.blocked > 0 ? <p className="fcp-dashboard-risk">Риск определён по флагу Blocked GitHub Project.</p> : null}</a>; })}</section></>; }

function TaskBoardCard({project,item,hermesOwnerOptionId}: Readonly<{project:ProjectTaskView;item:ProjectTaskView['tasks'][number];hermesOwnerOptionId?: string | undefined}>) { const attention = item.blocked === true || item.dependencyIssueIds.length > 0; return <a className="fcp-board-card" href={phaseHref('tasks',project.slug,item.itemId)}><header><span>GitHub #{item.issueId}</span>{attention ? <span className="fcp-board-attention"><AlertTriangle aria-hidden="true" size={13}/>Требует внимания</span> : null}</header><strong>{item.title}</strong><div><span>{readableAssignees(item, hermesOwnerOptionId)}</span><small>{item.blocked === true ? 'Blocked' : item.dependencyIssueIds.length > 0 ? `Зависимости: ${item.dependencyIssueIds.map((id) => `#${id}`).join(', ')}` : 'Следующий переход в GitHub Project'}</small></div><time>{item.targetDate === null ? 'Срок не задан' : date(item.targetDate)}</time></a>; }
export function TaskDetail({project,item,executorControl,hermesOwnerOptionId}: Readonly<{project:ProjectTaskView;item:ProjectTaskView['tasks'][number];executorControl?: ((task: ProjectTaskView['tasks'][number]) => ReactNode) | undefined;hermesOwnerOptionId?: string | undefined}>) {
  const blocked = item.blocked === null ? 'Статус блокировки не подтверждён' : item.blocked ? 'Заблокирована' : 'Не заблокирована';
  return <><ProjectHeader project={project} title={item.title} showTrackerState={false}/><section className="fcp-task-detail"><header><div className="fcp-detail-status"><span className="fcp-status neutral"><CircleDot aria-hidden="true" size={14}/>{item.statusOptionName ?? 'Без статуса'}</span></div><a href={item.url} target="_blank" rel="noreferrer">Открыть issue в GitHub ↗</a></header><dl className="fcp-task-facts"><div><dt>Исполнитель</dt><dd>{readableAssignees(item, hermesOwnerOptionId)}</dd></div><div><dt>Состояние</dt><dd>{blocked}</dd></div>{item.targetDate === null ? null : <div><dt>Срок</dt><dd>{date(item.targetDate)}</dd></div>}</dl>{executorControl?.(item)}</section></>;
}
export function Tasks({project,task,filter,executorControl,hermesOwnerOptionId}: Readonly<{project:ProjectTaskView|null;task:string|undefined;filter?:string|undefined;executorControl?: ((task: ProjectTaskView['tasks'][number]) => ReactNode) | undefined;hermesOwnerOptionId?: string | undefined}>) { if (project === null) return <Empty title="Нет доступных проектов"/>; const selected = project.tasks.find((item) => item.itemId === task); if (selected !== undefined) return <TaskDetail project={project} item={selected} executorControl={executorControl} hermesOwnerOptionId={hermesOwnerOptionId}/>; const blocked = project.tasks.filter((item) => item.blocked === true); const showBlocked = filter === 'blocked'; const visibleTasks = showBlocked ? blocked : project.tasks; return <><ProjectHeader project={project} title="Задачи"/><ContextTabs items={[{label:'Доска',href:phaseHref('tasks',project.slug),active:!showBlocked,count:project.tasks.length},{label:'Мои задачи',href:'#assignee-projection-unavailable',active:false,disabled:true},{label:'Заблокировано',href:phaseHref('tasks',project.slug,undefined,'blocked'),active:showBlocked,count:blocked.length}]}/><div className="fcp-section-head fcp-page-actions"><span>{showBlocked ? 'Заблокированные задачи · read-only snapshot' : 'Read-only · synchronized from the configured tracker'}</span></div><div className="fcp-board" aria-label={`${project.name} task board`}>{phaseAStages.map((stage) => { const items = visibleTasks.filter((item) => item.statusOptionName === stage); return <section className="fcp-board-column" key={stage}><header><div><h2>{stage}</h2><span>{items.length}</span></div><p>{stage === 'Backlog' ? 'Not committed' : stage === 'Ready' ? 'Ready to start' : stage === 'In Dev' ? 'Implementation' : stage === 'QA' ? 'Verification' : stage === 'Acceptance' ? 'PO decision' : 'Accepted scope'}</p></header><div>{items.length === 0 ? <p className="fcp-board-empty">Нет задач</p> : items.map((item) => <TaskBoardCard project={project} item={item} hermesOwnerOptionId={hermesOwnerOptionId} key={item.itemId}/>)}</div></section>; })}</div></>; }

type AgentRoutingPresentation = Readonly<{policy: AgentRoutingPolicy; version: string|null; provenance: string|null; createdAt: string|null; executorCatalog: AgentExecutorCatalog}>;
const routingClassLabel: Record<AgentRoute['taskClass'], string> = {
  manager_project_ops: 'Управление проектом', ordinary_implementation: 'Обычная реализация',
  ui_responsive: 'Интерфейс и адаптивность', complex_implementation: 'Сложная реализация',
  qa_audit: 'Проверка и аудит', architecture_design: 'Архитектура и дизайн',
  critical_decision: 'Критическое решение', release_preflight: 'Предрелизная проверка',
  protected_operation: 'Защищённая операция'
};
const routingExecutorLabel = (route: AgentRoute) => route.executor.kind === 'direct-agent' ? 'Hermes' : route.executor.id === 'codex-cli' ? 'Codex CLI' : 'CLI · недоступен';
const routingModelLabel = (route: AgentRoute) => `${route.model === 'gpt-5.6-sol' ? 'GPT-5.6 Sol' : 'GPT-5.6 Terra'} · ${route.effort === 'high' ? 'высокое усилие' : 'среднее усилие'}`;
const routingGateLabel: Record<AgentRoute['humanGate'], string> = {none:'Не требуется',product_visual:'Согласование UI/UX',architecture_decision:'Архитектурное решение',production_exact:'Точное production-подтверждение'};
const routingVersionLabel = (routing: AgentRoutingPresentation) => routing.version === null ? 'Базовая политика · ещё не сохранена' : `Активная версия ${routing.version.slice(0, 12)} · ${routing.provenance?.startsWith('control-plane:') ? 'Control Plane' : routing.provenance ?? 'зафиксированное происхождение'}`;

function HermesExecution({project, routing, canManage}: Readonly<{project: ProjectTaskView; routing: AgentRoutingPresentation; canManage: boolean}>) {
  const codexReady = routing.executorCatalog['codex-cli']?.available ?? false;
  return <section className="fcp-section fcp-hermes-execution"><div className="fcp-section-head"><div><h2>Исполнение Hermes</h2><span>{routingVersionLabel(routing)}</span></div><span>fai.agent-routing.v1</span></div><div className="fcp-hermes-execution-intro"><p>Hermes сам определяет класс задачи по политике и её контексту. Назначать класс вручную не требуется.</p><div className="fcp-hermes-runtime-status" aria-label="Доступность CLI"><span className={codexReady ? 'ready' : 'unavailable'}>Codex CLI · {codexReady ? 'готов' : 'runtime не подтверждён'}</span><span className="unavailable">Claude Code CLI · не подключён</span></div></div><div className="fcp-hermes-routing" aria-label="Матрица исполнения Hermes"><div className="fcp-hermes-routing-head"><span>Класс задачи</span><span>Исполнитель</span><span>Модель и усилие</span><span>Приёмка Hermes</span><span>Контроль человека</span></div>{routing.policy.routes.map((route) => <div className="fcp-hermes-routing-row" key={route.taskClass}><strong>{routingClassLabel[route.taskClass]}</strong><span data-label="Исполнитель">{routingExecutorLabel(route)}</span><span data-label="Модель и усилие">{routingModelLabel(route)}</span><span data-label="Приёмка Hermes">Обязательна</span><span data-label="Контроль человека">{routingGateLabel[route.humanGate]}</span></div>)}</div><AgentRoutingControl projectId={project.id} canManage={canManage} policy={routing.policy} executorCatalog={routing.executorCatalog}/></section>;
}

function HermesContext({context, project, canManage}: Readonly<{context: ProjectContextStatusView|null; project: ProjectTaskView; canManage: boolean}>) {
  return <div className="fcp-hermes-context-view"><div><h2>Контекст Hermes</h2><p>Собранный контекст для запусков Hermes</p></div><HermesContextControl projectId={project.id} canManage={canManage} context={context}/></div>;
}

export function Process({project, filter, routing, processPolicy, activeContext, canManageRouting, canManageContext}: Readonly<{project: ProjectTaskView|null; filter: string|undefined; routing: AgentRoutingPresentation; processPolicy: ProjectProcessPolicyView|null; activeContext: ProjectContextStatusView|null; canManageRouting: boolean; canManageContext: boolean}>) {
  if (project === null) return <Empty title="Нет доступных проектов"/>;
  const tab = filter === 'hermes' ? 'hermes' : filter === 'context' ? 'context' : 'stages';
  const stages = processPolicy?.policy.stages ?? [];
  const body = tab === 'hermes' ? <HermesExecution project={project} routing={routing} canManage={canManageRouting}/>
    : tab === 'context' ? <HermesContext context={activeContext} project={project} canManage={canManageContext}/>
      : stages.length === 0 ? <Empty title="Процесс не настроен"/> : <section className="fcp-section"><div className="fcp-section-head"><div><h2>Как проект проходит разработку</h2><span>Проектная политика процесса · только чтение</span></div><span>Версия {processPolicy?.version.slice(0, 12)}</span></div><ol className="fcp-protocol-flow" aria-label={`Протокол работы ${project.name}`}>{stages.map((stage, index) => {
        const next = stage.nextStageId === null ? null : stages.find((candidate) => candidate.id === stage.nextStageId)?.title ?? 'Не настроено';
        return <li key={stage.id}><header><span>{String(index + 1).padStart(2, '0')}</span><span className="fcp-status neutral"><CircleDot aria-hidden="true" size={14}/>Этап</span></header><h3>{stage.title}</h3><dl><div><dt>Ответственный</dt><dd>{stage.responsibility}</dd></div><div><dt>Режим / gate</dt><dd>{stage.gate}</dd></div><div><dt>Подтверждающие материалы</dt><dd>{stage.evidence}</dd></div></dl><footer>{next === null ? <><FileCheck2 aria-hidden="true" size={15}/><span>Завершение процесса</span></> : <><ArrowRight aria-hidden="true" size={15}/><span>Далее: {next}</span></>}</footer>{next === null ? null : <span className="fcp-protocol-connector" aria-hidden="true"/>}</li>;
      })}</ol></section>;
  return <><ProjectHeader project={project} title="Процесс"/><ContextTabs items={[{label:'Этапы',href:phaseHref('process',project.slug),active:tab === 'stages',count:stages.length},{label:'Исполнение Hermes',href:phaseHref('process',project.slug,undefined,'hermes'),active:tab === 'hermes'},{label:'Контекст Hermes',href:phaseHref('process',project.slug,undefined,'context'),active:tab === 'context'}]}/>{body}</>;
}
