import {readFile} from 'node:fs/promises';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it,vi} from 'vitest';
import {ProjectsFixture,type ProjectsFixtureState} from '../../tests/visual/projects-setup-fixtures.tsx';
import {Pr3Fixture,type Pr3FixtureState} from '../../tests/visual/pr3-fixtures.tsx';

vi.mock('next/navigation',()=>({useRouter:()=>({refresh:vi.fn(),push:vi.fn(),replace:vi.fn()})}));

const source=async(name:string)=>readFile(new URL(`./${name}`,import.meta.url),'utf8');

describe('Projects portfolio and setup vertical slice',()=>{
  it('keeps Roles and access as a scan-first membership portfolio with progressive mutations',async()=>{const [view,controls]=await Promise.all([source('phase-b-ui.tsx'),source('operator-controls.tsx')]);expect(view).toContain('<MembershipEditor');expect(view).toContain('<MembershipAddControl');expect(view).not.toContain('<AccessControls projectId={project.id}');expect(view).toContain("person.kind==='human'?'Человек':'Система'");expect(controls).toContain('Изменить членство: ${member.displayName} · ${projectName}');expect(controls).toContain('Добавить участника: ${projectName}');expect(controls).not.toContain('MembershipEditor({projectId');expect(controls).toContain('title="Добавить участника"');expect(controls).toContain('Выберите сотрудника');expect(controls).toContain('Изменения применяются только к этому проекту.');expect(controls).toContain("post(`/api/access/memberships/${member.membershipId}`,{role,active:true})");expect(controls).not.toContain('Членство активно');expect(controls).toContain("post('/api/access/onboarding'");expect(controls).toContain('<Dialog open={open}');});

  it('renders deterministic owner, read-only and empty Roles fixtures without a mutation panel',()=>{const states:Pr3FixtureState[]=['roles-owner','roles-read-only','roles-empty'];for(const state of states)expect(renderToStaticMarkup(<Pr3Fixture state={state}/>),state).toContain('Роли и доступы');const owner=renderToStaticMarkup(<Pr3Fixture state="roles-owner"/>);const readonly=renderToStaticMarkup(<Pr3Fixture state="roles-read-only"/>);const empty=renderToStaticMarkup(<Pr3Fixture state="roles-empty"/>);expect(owner.match(/class="fcp-secondary fcp-c-membership-add"/g)).toHaveLength(2);expect(owner.match(/Изменить членство/g)).toHaveLength(4);expect(readonly).toContain('Доступ только для просмотра');expect(readonly.match(/class="fcp-secondary fcp-c-membership-add"/g)).toHaveLength(1);expect(readonly.match(/Изменить членство/g)).toHaveLength(2);expect(empty).toContain('Участники ещё не добавлены.');expect(empty).not.toContain('Добавить участника');expect(empty).toContain('Доступ только для просмотра');});

  it('renders every deterministic portfolio/setup state without a separate production route',()=>{const states:ProjectsFixtureState[]=['zero','one','two','loading','error','partial','complete','integration-error','documents-empty','documents-loaded','documents-history','agent-connected','agent-offline','agent-degraded','read-only','command-pending','command-success','command-error'];for(const state of states){const html=renderToStaticMarkup(<ProjectsFixture state={state}/>);expect(html,`fixture ${state}`).toContain('Проекты');expect(html,`fixture ${state}`).not.toContain('Настройки проектов');}});

  it('renders compact zero/one/two portfolios with one primary Add action',()=>{const zero=renderToStaticMarkup(<ProjectsFixture state="zero"/>);const one=renderToStaticMarkup(<ProjectsFixture state="one"/>);const two=renderToStaticMarkup(<ProjectsFixture state="two"/>);expect(zero.match(/Добавить проект/g)).toHaveLength(1);expect(one.match(/<article class="fcp-c-project-row">/g)).toHaveLength(1);expect(two.match(/<article class="fcp-c-project-row">/g)).toHaveLength(2);expect(two).toContain('Настройка 2/5');expect(two).toContain('Настройка 5/5');});

  it('keeps future setup mutations locked and makes Documents the next step after binding',()=>{const partial=renderToStaticMarkup(<ProjectsFixture state="partial"/>);expect(partial).toContain('Настройка 2/5');expect(partial).toMatch(/aria-selected="true"[^>]*>Контекст<\/button>/);expect(partial).toMatch(/class="is-active"[^>]*>.*?<b>Документы<\/b>/);expect(partial).toContain('Загрузить документы');expect(partial).not.toContain('Установить ИИ-агента');expect(partial).not.toContain('Настроить контекст');expect(partial).not.toContain('Поставить задачу Hermes');expect(partial).toContain('Сначала завершите текущий шаг: Документы.');});

  it('renders five setup tabs, loaded/empty documents, agent failures and read-only access',()=>{const partial=renderToStaticMarkup(<ProjectsFixture state="partial"/>);const loaded=renderToStaticMarkup(<ProjectsFixture state="documents-loaded"/>);const offline=renderToStaticMarkup(<ProjectsFixture state="agent-offline"/>);const readonly=renderToStaticMarkup(<ProjectsFixture state="read-only"/>);for(const label of ['Обзор','Интеграции','Контекст','Агент','Доступ'])expect(partial).toContain(`>${label}</button>`);expect(partial).toContain('Документы ещё не загружены.');expect(loaded).toContain('Паспорт проекта.pdf');expect(offline).toContain('Не отвечает');expect(readonly).toContain('Доступ только для просмотра');expect(readonly).not.toContain('>Удалить проект</button>');});

  it('renders pending, success and error command states through the single async owner',()=>{const pending=renderToStaticMarkup(<ProjectsFixture state="command-pending"/>);const success=renderToStaticMarkup(<ProjectsFixture state="command-success"/>);const error=renderToStaticMarkup(<ProjectsFixture state="command-error"/>);expect(pending).toContain('aria-busy="true"');expect(pending).toContain('Сохраняем…');expect(success).toContain('Изменение сохранено.');expect(error).toContain('role="alert"');expect(error).toContain('Данные не изменены.');});

  it('keeps the settings route while presenting compact Projects rows',async()=>{const [view,navigation]=await Promise.all([source('phase-b-ui.tsx'),source('phase-a-ui.tsx')]);expect(navigation).toContain("settings:'Проекты'");expect(view).toContain('title="Проекты"');expect(view).toContain('<ProjectListRow');expect(view).toContain('Настройка ${grouped.complete}/5');expect(view).toContain('/?view=settings&setup=');expect(view).not.toContain('function SettingsProject');expect(view).not.toContain('ProjectDeleteControl');expect(view).not.toContain('ProjectDocumentsEditor');});

  it('shows deterministic empty, loading, error and invalid-slug recovery states',async()=>{const view=await source('phase-b-ui.tsx');expect(view).toContain("projectsState==='loading'?<Skeleton");expect(view).toContain("projectsState==='error'?<ErrorState");expect(view).toContain('title="Проектов пока нет"');expect(view).toContain('title="Проект не найден"');expect(view).toContain('Вернуться к проектам');});

  it('uses five accessible project tabs and the approved setup rail',async()=>{const [wizard,foundation]=await Promise.all([source('project-wizard.tsx'),source('../ui/foundation.tsx')]);for(const label of ['Обзор','Интеграции','Контекст','Агент','Доступ'])expect(wizard).toContain(`label:'${label}'`);for(const label of ['Репозиторий','Трекер','Документы','Агент','Проверка'])expect(wizard).toContain(`'${label}'`);expect(wizard).toContain('<SetupRail');expect(foundation).toContain('role="tablist"');expect(foundation).toContain("event.key==='ArrowRight'");expect(foundation).toContain("event.key==='Home'");expect(foundation).toContain('role="tabpanel"');});

  it('regroups every existing setup command without changing its endpoint or idempotency owner',async()=>{const wizard=await source('project-wizard.tsx');for(const command of ["action:'confirm_process'","action:'skip_team'","action:'skip_communications'","action:'install'","action:'confirm_and_start'","action:'create_and_start'"])expect(wizard).toContain(command);for(const seam of ['/wizard-progress','/runtime','/agent-profile','/tracker-preparation','/api/approvals/','/api/tasks/executor'])expect(wizard).toContain(seam);expect(wizard).toContain('<AccessControls');expect(wizard).toContain('<TelegramSettingsControl');expect(wizard).toContain('<ProjectDocumentsEditor');expect(wizard).toContain('<FirstTask item={item}/>');});

  it('keeps one document upload path and lists loaded documents',async()=>{const [wizard,control]=await Promise.all([source('project-wizard.tsx'),source('operator-controls.tsx')]);expect(wizard).toContain('documents.activeDocuments.map');expect(wizard).toContain('Скачать');expect(control).toContain('Загрузить документы');expect(control).toContain('Добавить ещё файл');expect(control).not.toContain('>Очистить<');expect(control).not.toContain('export function ProjectDocumentUploadControl');expect(control).toContain('upload_timeout');});

  it('renders all document types as one visible accessible choice group',async()=>{const empty=renderToStaticMarkup(<ProjectsFixture state="documents-empty"/>);for(const label of ['Паспорт проекта','Техническое задание','Архитектура','Прочее'])expect(empty).toContain(`>${label}</button>`);expect(empty).toContain('role="group" aria-label="Тип документа 1"');expect(empty).toContain('aria-pressed="true">Паспорт проекта</button>');for(const label of ['Техническое задание','Архитектура','Прочее'])expect(empty).toContain(`aria-pressed="false">${label}</button>`);expect(empty).not.toContain('<select');const control=await source('operator-controls.tsx');expect(control).toContain("onChange={(category)=>update(row.id,{category})}");});

  it('shows only the authoritative fixed document version while retaining supplemental documents',()=>{const history=renderToStaticMarkup(<ProjectsFixture state="documents-history"/>);expect(history).toContain('Техническое задание · актуальное.pdf');expect(history).not.toContain('Техническое задание · архив.pdf');expect(history).toContain('Приложение A.pdf');expect(history).toContain('Приложение B.pdf');});

  it('keeps destructive action only in the final Danger Zone with exact-name confirmation',async()=>{const [wizard,control,foundation]=await Promise.all([source('project-wizard.tsx'),source('operator-controls.tsx'),source('../ui/foundation.tsx')]);expect(wizard).toContain('<DangerZone');expect(wizard.indexOf('<DangerZone')).toBeGreaterThan(wizard.indexOf('const accessPanel'));expect(control).toContain('confirmation!==projectName');expect(control).toContain('<Dialog open={confirming}');expect(foundation).toContain('role="dialog"');expect(foundation).toContain("event.key==='Escape'");expect(foundation).toContain("event.key!=='Tab'");});

  it('renders capability-aware read-only setup while retaining owner and operator actions',async()=>{const wizard=await source('project-wizard.tsx');expect(wizard).toContain("const canManage=role==='project_owner'");expect(wizard).toContain("const canStart=role==='project_owner'||role==='operator'");expect(wizard).toContain('<ReadOnlyNotice/>');expect(wizard).toContain('canManage?<ProjectDeleteControl');});

  it('loads existing projections once and per-project facts concurrently',async()=>{const page=await source('../../app/page.tsx');expect(page).toContain('listProjectOperatorEvidenceViews(database, session.actorId, evidenceSections)');expect(page).toContain('listProjectSourceViews(database, session.actorId)');expect(page).toContain('Promise.all(projects.map(async (project)');expect(page).toContain('<PhaseB view={view} projects={phaseBProjects}');});
});
