import type {ProjectContextStatusView, ProjectExecutionModeView, ProjectProcessPolicyView, ProjectTaskView} from '@fai-control-plane/db';
import type {AgentExecutorCatalog, AgentRoutingPolicy,ProjectProcessPolicy} from '@fai-control-plane/domain';
import type {ReactNode} from 'react';
import {ArrowRight,ChevronRight,FileCheck2} from 'lucide-react';
import {buildPortfolio} from './portfolio-view.ts';
import {dashboardProjection,readableAssignees,type PhaseAState} from './phase-a-view.ts';
import {AgentRoutingControl, HermesContextControl, ProjectExecutionModeControl} from './operator-controls.tsx';
import {TokenTotal} from './token-total.tsx';
import {TaskBoard} from './task-board.tsx';
import {EmptyState,ErrorState,PageHeader,ProjectPanel,ProjectSection,ReadOnlyNotice,StatusIndicator} from '../ui/foundation.tsx';
import {WorkspaceLink} from '../ui/workspace-link.tsx';
import {phaseHref} from './navigation.ts';
import {TaskProjectSelector} from './task-project-selector.tsx';
export {phaseHref,type PhaseArea} from './navigation.ts';
export {Shell} from './workspace-shell.tsx';

const date = (value: string) => new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Moscow'}).format(new Date(`${value}T12:00:00.000Z`));

const trackerLabel = (project: ProjectTaskView): readonly ['success'|'warning'|'danger'|'neutral',string] => project.tracker.freshness === 'fresh' ? ['success','Данные таск-трекера подтверждены.'] : project.tracker.freshness === 'stale' ? ['warning','Данные таск-трекера устарели.'] : project.tracker.freshness === 'error' ? ['danger','Таск-трекер пока не подтвердил обновление.'] : ['neutral','Таск-трекер ещё не подтверждён.'];
function SourceNotice({project}:Readonly<{project:ProjectTaskView}>){const [tone,label]=trackerLabel(project);return project.tracker.freshness==='fresh'?null:<p className={`fcp-c-source-notice is-${tone}`} role={tone==='danger'?'alert':'note'}>{label}{project.tracker.observedAt===null?'':' Последние подтверждённые данные сохранены.'}</p>;}

const stateLegend:readonly Readonly<{id:PhaseAState;label:string}>[]=[{id:'accepted',label:'Принято'},{id:'review',label:'На проверке'},{id:'in-progress',label:'В работе'},{id:'not-started',label:'Не начато'}];
function TaskCountProgress({project,source}:Readonly<{project:ReturnType<typeof buildPortfolio>[number];source:ProjectTaskView}>){const projection=dashboardProjection(source.tasks);return <section className="fcp-c-task-count"><p><strong>{projection.states.accepted} / {projection.total}</strong><span>задач принято</span></p><div className="fcp-c-task-count-bar" role="progressbar" aria-label={`Распределение задач проекта ${project.name}`} aria-valuemin={0} aria-valuemax={Math.max(projection.total,1)} aria-valuenow={projection.states.accepted} aria-valuetext={stateLegend.map(({id,label})=>`${label}: ${projection.states[id]}`).join(', ')}>{stateLegend.map(({id})=><i className={`is-${id}`} style={{width:`${projection.total===0?0:projection.states[id]/projection.total*100}%`}} key={id}/>)}</div><ul aria-label={`Легенда задач ${project.name}`}>{stateLegend.map(({id,label})=><li className={`is-${id}`} key={id}><i aria-hidden="true"/>{label} {projection.states[id]}</li>)}</ul></section>;}
export function Dashboard({projects}: Readonly<{projects:readonly ProjectTaskView[]}>) { const portfolio=buildPortfolio(projects); return <div className="fcp-c-overview"><PageHeader title="Обзор" detail="Портфель проектов, текущий фокус и подтверждённые риски."/>{portfolio.length===0?<EmptyState title="Нет доступных проектов" detail="После подключения таск-трекера здесь появится портфель."/>:<div className="fcp-c-project-panel-grid is-stack" aria-label="Портфель проектов">{portfolio.map((project)=>{const source=projects.find((item)=>item.id===project.id)!;const tone=project.health==='steady'?'success':project.health==='attention'?'warning':'danger';const state=project.health==='steady'?'Состояние устойчивое':project.health==='attention'?'Требует внимания':'Данные не подтверждены';return <ProjectPanel name={project.name} status={<StatusIndicator tone={tone}>{state}</StatusIndicator>} action={<WorkspaceLink className="fcp-c-project-panel-action" href={phaseHref('tasks',source.slug)}>Открыть задачи<ChevronRight aria-hidden="true" size={16}/></WorkspaceLink>} key={project.id}><TaskCountProgress project={project} source={source}/><dl className="fcp-c-overview-facts"><div><dt>Открыто</dt><dd>{project.open}</dd></div><div><dt>Заблокировано</dt><dd>{project.blocked??'Не подтверждено'}</dd></div><div><dt>Контроль</dt><dd>{project.nextControl===null?'Не назначен':date(project.nextControl)}</dd></div><div><dt>Токены проекта</dt><dd><TokenTotal total={source.usage?.combinedTotal}/></dd></div></dl><p className="fcp-c-overview-focus">{project.decision===null?'Следующая контрольная точка пока не определена.':`${project.decision.title} · ${project.decision.detail}`}</p></ProjectPanel>;})}</div>}</div>; }

function TaskHeader({projects,project,title}: Readonly<{projects:readonly ProjectTaskView[];project:ProjectTaskView;title:string}>) { return <PageHeader title={title} detail="Задачи выбранного проекта в таск-трекере." action={<TaskProjectSelector projects={projects} project={project}/>}/>; }
function TaskTabs({project,blocked,active}:Readonly<{project:ProjectTaskView;blocked:number;active:boolean}>){return <nav className="fcp-c-task-tabs" aria-label="Разделы задач"><WorkspaceLink href={phaseHref('tasks',project.slug)} aria-current={active?'page':undefined}>Доска <span>{project.tasks.length}</span></WorkspaceLink><WorkspaceLink href={phaseHref('tasks',project.slug,undefined,'blocked')} aria-current={active?undefined:'page'}>Заблокировано <span>{blocked}</span></WorkspaceLink></nav>;}
function TaskDetail({projects,project,item,executorControl,hermesOwnerOptionId,canManage}: Readonly<{projects:readonly ProjectTaskView[];project:ProjectTaskView;item:ProjectTaskView['tasks'][number];executorControl?: ((task: ProjectTaskView['tasks'][number]) => ReactNode) | undefined;hermesOwnerOptionId?: string | undefined;canManage:boolean}>) { const blocked = item.blocked === null ? 'Не подтверждено' : item.blocked ? 'Заблокирована' : 'Не заблокирована'; return <><TaskHeader projects={projects} project={project} title={item.title}/><SourceNotice project={project}/><section className="fcp-c-task-detail"><header><StatusIndicator tone={item.blocked===true?'warning':'neutral'}>{item.statusOptionName ?? 'Без статуса'}</StatusIndicator><a href={item.url} target="_blank" rel="noreferrer">Открыть задачу в GitHub ↗</a></header><dl><div><dt>Исполнитель</dt><dd>{readableAssignees(item, hermesOwnerOptionId)}</dd></div><div><dt>Состояние</dt><dd>{blocked}</dd></div><div><dt>Токены задачи</dt><dd><TokenTotal total={project.usage?.taskTotals[item.itemId]}/></dd></div>{item.targetDate === null ? null : <div><dt>Срок</dt><dd>{date(item.targetDate)}</dd></div>}</dl>{canManage?executorControl?.(item):<ReadOnlyNotice/>}</section></>; }
export function Tasks({projects,project,task,filter,executorControl,hermesOwnerOptionId,invalidProject=false,canManage=false}: Readonly<{projects:readonly ProjectTaskView[];project:ProjectTaskView|null;task:string|undefined;filter?:string|undefined;executorControl?: ((task: ProjectTaskView['tasks'][number]) => ReactNode) | undefined;hermesOwnerOptionId?: string | undefined;invalidProject?:boolean;canManage?:boolean}>) { if(invalidProject)return <><PageHeader title="Задачи" detail="Задачи выбранного проекта в таск-трекере."/><ErrorState title="Проект не найден" detail="Проверьте ссылку или выберите доступный проект." action={<WorkspaceLink className="fcp-secondary" href={phaseHref('tasks')}>К задачам</WorkspaceLink>}/></>;if(project===null)return <><PageHeader title="Задачи" detail="Задачи выбранного проекта в таск-трекере."/><EmptyState title="Нет доступных проектов" detail="После подключения таск-трекера задачи появятся здесь."/></>;const selected=project.tasks.find((item)=>item.itemId===task);if(task!==undefined&&selected===undefined)return <><TaskHeader projects={projects} project={project} title="Задачи"/><ErrorState title="Задача не найдена" detail="Возможно, она изменилась в таск-трекере. Вернитесь к актуальной доске." action={<WorkspaceLink className="fcp-secondary" href={phaseHref('tasks',project.slug)}>Открыть доску</WorkspaceLink>}/></>;if(filter!==undefined&&filter!=='blocked')return <><TaskHeader projects={projects} project={project} title="Задачи"/><ErrorState title="Фильтр не найден" detail="Откройте стандартный вид задач или список заблокированных." action={<WorkspaceLink className="fcp-secondary" href={phaseHref('tasks',project.slug)}>Открыть доску</WorkspaceLink>}/></>;if(selected!==undefined)return <TaskDetail projects={projects} project={project} item={selected} executorControl={executorControl} hermesOwnerOptionId={hermesOwnerOptionId} canManage={canManage}/>;const blocked=project.tasks.filter((item)=>item.blocked===true);const showBlocked=filter==='blocked';const visibleTasks=showBlocked?blocked:project.tasks;return <><TaskHeader projects={projects} project={project} title="Задачи"/><SourceNotice project={project}/><TaskTabs project={project} blocked={blocked.length} active={!showBlocked}/>{project.tracker.freshness==='unavailable'?<EmptyState title="Таск-трекер ещё не подтверждён" detail="Подключите и проверьте источник задач в настройках проекта."/>:visibleTasks.length===0?<EmptyState title={showBlocked?'Заблокированных задач нет':'Задач пока нет'} detail={showBlocked?'В доступном снимке нет задач с подтверждённой блокировкой.':'Таск-трекер не вернул задач в последнем подтверждённом снимке.'}/>:<TaskBoard project={project} tasks={visibleTasks} hermesOwnerOptionId={hermesOwnerOptionId}/>}</>; }

type AgentRoutingPresentation = Readonly<{policy:AgentRoutingPolicy;executorCatalog:AgentExecutorCatalog}>;
export type ProcessProject = Readonly<{project:ProjectTaskView;processPolicy:ProjectProcessPolicyView|null;executionMode:ProjectExecutionModeView;routing:AgentRoutingPresentation;context:ProjectContextStatusView|null;canManageRouting:boolean;canManageContext:boolean}>;
export function ProcessRail({stages,label}:Readonly<{stages:ProjectProcessPolicy['stages'];label:string}>){return <ol className="fcp-c-process-rail" aria-label={label}>{stages.map((stage,index)=>{const next=stage.nextStageId===null?null:stages.find((candidate)=>candidate.id===stage.nextStageId)?.title??null;return <li key={stage.id}><span>{index+1}</span><div><strong>{stage.title}</strong><small>{stage.responsibility.replaceAll('ИИ агент','ИИ-агент')}</small></div>{next===null?<FileCheck2 aria-label="Завершение" size={16}/>:<><ArrowRight aria-hidden="true" size={15}/><small>{next}</small></>}</li>;})}</ol>;}
/** Kept as the established process composition used by the approved Setup slice. */
export const ProcessStages=ProcessRail;
function ProcessProjectSection({item}:Readonly<{item:ProcessProject}>){const {project,processPolicy,executionMode,routing,context,canManageRouting,canManageContext}=item;const stages=processPolicy?.policy.stages??[];const configured=stages.length>0;const routingReady=routing.executorCatalog['codex-cli']?.available??false;return <ProjectSection name={project.name} status={<StatusIndicator tone={!configured?'warning':executionMode.mode==='autonomous'?'info':'neutral'}>{!configured?'Требует настройки':executionMode.mode==='autonomous'?'Автономный режим':'Ручной режим'}</StatusIndicator>}><div className="fcp-c-process-project-body"><SourceNotice project={project}/><div className="fcp-c-process-facts" aria-label={`Состояние процесса ${project.name}`}><div><span>Процесс</span><strong>{configured?`${stages.length} этапов`:'Не настроен'}</strong></div><div><span>Выполнение</span><strong>{executionMode.mode==='autonomous'?'Автономно':'Только вручную'}</strong></div><div><span>ИИ-агент</span><strong>{routingReady?'Codex CLI готов':'Codex CLI не подключён'}</strong></div></div>{configured?<><ProcessRail stages={stages} label={`Процесс ${project.name}`}/><div className="fcp-c-process-actions"><ProjectExecutionModeControl projectId={project.id} mode={executionMode} canManage={canManageContext}/><AgentRoutingControl projectId={project.id} projectName={project.name} canManage={canManageRouting} policy={routing.policy} executorCatalog={routing.executorCatalog}/><HermesContextControl projectId={project.id} canManage={canManageContext} context={context}/></div></>:<p className="fcp-c-readonly" role="note">Сначала завершите настройку проекта. Управление выполнением, ИИ-агентом и контекстом станет доступно после проверки.</p>}</div></ProjectSection>;}
export function Process({projects}: Readonly<{projects:readonly ProcessProject[]}>) { return <div className="fcp-c-process"><PageHeader title="Процесс" detail="Подтверждённый порядок работы и готовность каждого проекта."/>{projects.length===0?<EmptyState title="Нет доступных проектов" detail="После подключения проекта здесь появится его процесс."/>:<div className="fcp-c-project-sections" aria-label="Процессы проектов">{projects.map((item)=><ProcessProjectSection item={item} key={item.project.id}/>)}</div>}</div>; }
