import {createHash} from 'node:crypto';
import type {ProjectAgentProfileView,ProjectHermesRuntimeSetupView,ProjectOperatorEvidenceView,ProjectSourceView,ProjectTaskView,ProjectTrackerCapabilities,ProjectTrackerPreparationView,ProjectWizardProgress,WorkspaceHumanActorView} from '@fai-control-plane/db';
import {Bot} from 'lucide-react';
import {ProjectChannelSettings,ProjectMembershipManager} from './operator-controls.tsx';
import {ProjectSetupWizard} from './project-wizard.tsx';
import {projectActiveDocuments,projectSetupGroups} from './project-setup-state.ts';
import type {IntegrationConfig} from './integration-config.ts';
import {phaseHref} from './phase-a-ui.tsx';
import {DividerList,EmptyState,ErrorState,PageHeader,ProjectListRow,ProjectSection,ReadOnlyNotice,Skeleton,StatusIndicator} from '../ui/foundation.tsx';
import {WorkspaceLink} from '../ui/workspace-link.tsx';

export type PhaseBView='conversations'|'people'|'systems'|'settings';
export type PhaseBProject=Readonly<{project:ProjectTaskView;evidence:ProjectOperatorEvidenceView|null;sources:readonly ProjectSourceView[];config:IntegrationConfig;agentProfile:ProjectAgentProfileView|null;runtimeSetup:ProjectHermesRuntimeSetupView|null;trackerCapabilities:ProjectTrackerCapabilities|null;trackerPreparation:ProjectTrackerPreparationView|null;wizardProgress:ProjectWizardProgress|null}>;
type Props=Readonly<{view:PhaseBView;projects:readonly PhaseBProject[];actorId:string;setup:string|undefined;workspacePeople:readonly WorkspaceHumanActorView[];projectsState?:'ready'|'loading'|'error'}>;

function EmptyProjects(){return <EmptyState title="Нет доступных проектов" detail="После подключения проекты появятся здесь."/>;}

const systemState=(item:PhaseBProject):readonly ['success'|'warning'|'danger'|'neutral'|'info',string,string]=>{const runtime=item.runtimeSetup?.status;if(runtime==='error')return ['danger','ИИ-агент не отвечает','Подключение не подтвердило готовность.'];if(runtime==='installing')return ['info','Настраивается','ИИ-агент устанавливается.'];if(runtime==='auth_required')return ['warning','Требует авторизации','Нужно подтвердить доступ ИИ-агента.'];if(item.agentProfile?.status==='error')return ['warning','Работает с ограничениями','Профиль ИИ-агента требует проверки.'];if(runtime==='ready')return ['success','Готов к работе','ИИ-агент проекта.'];if(item.config.hermes)return ['neutral','Подключён','Готовность пока не подтверждена.'];return ['warning','Не настроен','ИИ-агент проекта ещё не подключён.'];};
function Systems({projects}:Readonly<{projects:readonly PhaseBProject[]}>){return <div className="fcp-c-portfolio-page"><PageHeader title="ИИ-агенты и системы" detail="Подтверждённая готовность рабочих систем по каждому проекту."/>{projects.length===0?<EmptyProjects/>:<div className="fcp-c-project-sections">{projects.map((item)=>{const [tone,label,detail]=systemState(item);return <ProjectSection name={item.project.name} status={<StatusIndicator tone={tone}>{label}</StatusIndicator>} key={item.project.id}><DividerList label={`Системы проекта ${item.project.name}`}><div className="fcp-c-system-row"><Bot aria-hidden="true" size={18}/><div><strong>ИИ-агент</strong><span>{detail}</span></div><WorkspaceLink href={phaseHref('tasks',item.project.slug)}>Перейти к задачам</WorkspaceLink></div></DividerList></ProjectSection>;})}</div>}</div>;}

function Conversations({projects,actorId}:Readonly<{projects:readonly PhaseBProject[];actorId:string}>){return <div className="fcp-c-portfolio-page"><PageHeader title="Чаты" detail="Два изолированных канала проекта: внутренний и клиентский."/>{projects.length===0?<EmptyProjects/>:<div className="fcp-c-project-sections">{projects.map(({project,evidence,config})=>{const people=evidence?.people??[];const canManage=people.some((person)=>person.actorId===actorId&&person.active&&person.role==='project_owner');return <ProjectSection name={project.name} key={project.id}><ProjectChannelSettings projectId={project.id} projectName={project.name} channels={config.channels} canManage={canManage}/>{canManage?null:<ReadOnlyNotice/>}</ProjectSection>;})}</div>}</div>;}

function People({projects,actorId,workspacePeople}:Readonly<{projects:readonly PhaseBProject[];actorId:string;workspacePeople:readonly WorkspaceHumanActorView[]}>){return <div className="fcp-c-portfolio-page"><PageHeader title="Роли и доступы" detail="Участники и управление доступом по каждому проекту."/>{projects.length===0?<EmptyProjects/>:<div className="fcp-c-project-sections">{projects.map(({project,evidence})=>{const people=evidence?.people??[];const canManage=people.some((person)=>person.actorId===actorId&&person.active&&person.role==='project_owner');return <ProjectSection name={project.name} key={project.id}><ProjectMembershipManager projectId={project.id} projectName={project.name} canManage={canManage} members={people} workspacePeople={workspacePeople}/></ProjectSection>;})}</div>}</div>;}

export const projectDocumentState=({project,sources}:PhaseBProject)=>{const projectSources=sources.filter((source)=>source.projectId===project.id);const documents=projectActiveDocuments(projectSources);const fingerprint=createHash('sha256').update(documents.activeDocuments.slice().sort((left,right)=>left.kind.localeCompare(right.kind)||left.sha256.localeCompare(right.sha256)).map(({kind,sha256})=>`${kind}:${sha256}`).join('\n')).digest('hex');return {projectSources,...documents,fingerprint};};

const projectViewSetup=(item:PhaseBProject)=>{const documents=projectDocumentState(item);const contextCurrent=item.agentProfile?.status==='ready'&&item.agentProfile.documentFingerprint===documents.fingerprint;const trackerBound=item.project.tracker.sourceUrl!==null&&item.project.tracker.freshness!=='error';return {documents,...projectSetupGroups(item,documents.documentsReady,contextCurrent,trackerBound)};};
const shortRepository=(value:string)=>value.replace(/^https:\/\/github\.com\//,'').replace(/\/$/,'')||'Репозиторий не подтверждён';
const dateTime=(value:string|null)=>value===null?'Не подтверждена':new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}).format(new Date(value));
const agentFact=(item:PhaseBProject)=>item.runtimeSetup?.status==='ready'?'ИИ-агент подключён':item.runtimeSetup?.status==='error'?'ИИ-агент не отвечает':['installing','auth_required'].includes(item.runtimeSetup?.status??'')?'ИИ-агент настраивается':'ИИ-агент не настроен';
function ProjectPortfolioRow({item}:Readonly<{item:PhaseBProject}>){const {project}=item;const grouped=projectViewSetup(item);const hasError=project.tracker.freshness==='error'||item.runtimeSetup?.status==='error'||item.agentProfile?.status==='error';const healthy=grouped.complete===6&&!hasError;const status=<StatusIndicator tone={hasError?'danger':healthy?'success':'warning'}>{hasError?'Требует проверки':healthy?'Готов к работе':'Требует настройки'}</StatusIndicator>;return <ProjectListRow name={project.name} status={status} setup={`Настройка ${grouped.complete}/6`} facts={[shortRepository(project.repositoryUrl),project.tracker.sourceUrl===null?'Таск-трекер не подключён':'Таск-трекер подключён',agentFact(item),`Синхронизация: ${dateTime(project.tracker.observedAt)}`]} href={`/projects?setup=${encodeURIComponent(project.slug)}`} nextAction={healthy?'Открыть проект':'Продолжить настройку'}/>;}

function Projects({projects,setup,actorId,workspacePeople,projectsState='ready'}:Readonly<{projects:readonly PhaseBProject[];setup:string|undefined;actorId:string;workspacePeople:readonly WorkspaceHumanActorView[];projectsState?:'ready'|'loading'|'error'}>){const ordered=[...projects].sort((left,right)=>projectViewSetup(left).complete-projectViewSetup(right).complete);if(setup===undefined)return <div className="fcp-projects"><PageHeader title="Проекты" detail="Готовность подключений и следующий безопасный шаг." action={<WorkspaceLink className="fcp-primary" href="/projects?setup=create">Добавить проект</WorkspaceLink>}/>{projectsState==='loading'?<Skeleton/>:projectsState==='error'?<ErrorState detail="Сохранённые проекты не изменены. Обновите страницу и повторите." action={<WorkspaceLink className="fcp-secondary" href="/projects">Повторить</WorkspaceLink>}/>:projects.length===0?<EmptyState title="Проектов пока нет" detail="Подключите репозиторий и таск-трекер, чтобы начать настройку."/>:<DividerList label="Проекты">{ordered.map((item)=><ProjectPortfolioRow item={item} key={item.project.id}/>)}</DividerList>}</div>;
  const incomplete=ordered.filter((item)=>!projectViewSetup(item).setup.complete);const selected=setup==='new'?(incomplete[0]??ordered[0]??null):setup==='create'?null:projects.find(({project})=>project.slug===setup)??null;const creating=setup==='create';if(!creating&&selected===null)return <div className="fcp-projects"><PageHeader title="Проекты"/><ErrorState title="Проект не найден" detail="Возможно, проект удалён или адрес изменился." action={<WorkspaceLink className="fcp-secondary" href="/projects">Вернуться к проектам</WorkspaceLink>}/></div>;const contextCurrent=selected!==null&&selected.agentProfile?.status==='ready'&&selected.agentProfile.documentFingerprint===projectDocumentState(selected).fingerprint;return <div className="fcp-projects fcp-project-detail"><ProjectSetupWizard item={selected} creating={creating} contextCurrent={contextCurrent} actorId={actorId} workspacePeople={workspacePeople}/></div>;}

export function PhaseB(props:Props){switch(props.view){case'conversations':return <Conversations projects={props.projects} actorId={props.actorId}/>;case'people':return <People projects={props.projects} actorId={props.actorId} workspacePeople={props.workspacePeople}/>;case'systems':return <Systems projects={props.projects}/>;case'settings':return <Projects projects={props.projects} setup={props.setup} actorId={props.actorId} workspacePeople={props.workspacePeople} projectsState={props.projectsState??'ready'}/>;}}
