'use client';

import {TokenTotal} from './token-total.tsx';
import {useState} from 'react';
import {AlertTriangle} from 'lucide-react';
import type {ProjectTaskView} from '@fai-control-plane/db';
import {phaseAStages,readableAssignees} from './phase-a-view.ts';
import {phaseHref} from './navigation.ts';
import {WorkspaceLink} from '../ui/workspace-link.tsx';

type Task=ProjectTaskView['tasks'][number];
const date=(value:string)=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Moscow'}).format(new Date(`${value}T12:00:00.000Z`));
const taskHref=(project:string,task:string)=>phaseHref('tasks',project,task);

export function TaskBoardCard({project,item,hermesOwnerOptionId}:Readonly<{project:ProjectTaskView;item:Task;hermesOwnerOptionId?:string|undefined}>){const attention=item.blocked===true||item.dependencyIssueIds.length>0;const detail=item.blocked===true?'Заблокирована':item.dependencyIssueIds.length>0?'Есть зависимость':'Готова к следующему переходу';return <WorkspaceLink className="fcp-c-task-card" href={taskHref(project.slug,item.itemId)}><header>{attention?<span className="fcp-c-task-attention"><AlertTriangle aria-hidden="true" size={13}/>Требует внимания</span>:<span>Задача</span>}<time>{item.targetDate===null?'Срок не задан':date(item.targetDate)}</time></header><strong>{item.title}</strong><div><span>{readableAssignees(item,hermesOwnerOptionId)}</span><small>{detail}</small></div><small>Токены: <TokenTotal total={project.usage?.taskTotals[item.itemId]}/></small></WorkspaceLink>;}

export function TaskBoard({project,tasks,hermesOwnerOptionId}:Readonly<{project:ProjectTaskView;tasks:readonly Task[];hermesOwnerOptionId?:string|undefined}>){const [stage,setStage]=useState<typeof phaseAStages[number]>(phaseAStages.find((candidate)=>tasks.some((item)=>item.statusOptionName===candidate))??phaseAStages[0]);const itemsFor=(candidate:string)=>tasks.filter((item)=>item.statusOptionName===candidate);const stageBase=`task-board-${project.id}`;const move=(index:number,nextIndex:number)=>{const candidate=phaseAStages[(nextIndex+phaseAStages.length)%phaseAStages.length]!;setStage(candidate);requestAnimationFrame(()=>document.getElementById(`${stageBase}-tab-${(nextIndex+phaseAStages.length)%phaseAStages.length}`)?.focus());};const onKeyDown=(event:React.KeyboardEvent<HTMLButtonElement>,index:number)=>{if(event.key==='ArrowRight'){event.preventDefault();move(index,index+1);}else if(event.key==='ArrowLeft'){event.preventDefault();move(index,index-1);}else if(event.key==='Home'){event.preventDefault();move(index,0);}else if(event.key==='End'){event.preventDefault();move(index,phaseAStages.length-1);}};return <div className="fcp-c-task-board-wrap"><div className="fcp-c-task-mobile-stages" role="tablist" aria-label="Этапы задач">{phaseAStages.map((candidate,index)=>{const count=itemsFor(candidate).length;const tabId=`${stageBase}-tab-${index}`;const panelId=`${stageBase}-panel-${index}`;return <button type="button" id={tabId} role="tab" aria-selected={stage===candidate} aria-controls={panelId} tabIndex={stage===candidate?0:-1} onClick={()=>setStage(candidate)} onKeyDown={(event)=>onKeyDown(event,index)} key={candidate}>{candidate}<span>{count}</span></button>;})}</div><div className="fcp-c-task-board" aria-label={`Задачи ${project.name}`}>{phaseAStages.map((candidate)=>{const items=itemsFor(candidate);return <section className="fcp-c-task-column" key={candidate}><header><h2>{candidate}</h2><span>{items.length}</span></header><div>{items.length===0?<p>Нет задач</p>:items.map((item)=><TaskBoardCard project={project} item={item} hermesOwnerOptionId={hermesOwnerOptionId} key={item.itemId}/>)}</div></section>;})}</div>{phaseAStages.map((candidate,index)=><section id={`${stageBase}-panel-${index}`} className="fcp-c-task-mobile-list" role="tabpanel" aria-labelledby={`${stageBase}-tab-${index}`} hidden={stage!==candidate} key={candidate}>{itemsFor(candidate).length===0?<p>Нет задач на этом этапе.</p>:itemsFor(candidate).map((item)=><TaskBoardCard project={project} item={item} hermesOwnerOptionId={hermesOwnerOptionId} key={item.itemId}/>)}</section>)}</div>;}
