import Link from 'next/link';
import type {ReactNode} from 'react';
import {
  Activity, Bot, BriefcaseBusiness, CircleHelp, FileCheck2, MessagesSquare,
  Milestone, MoreHorizontal, ServerCog, ShieldCheck, SquareCheckBig, UsersRound
} from 'lucide-react';
import type {AccessData, HealthData, OperatorLoad, OperatorProjectSlug, PortfolioData, ProjectData, RunsData} from './operator-data';

type Area = 'portfolio' | 'delivery' | 'conversations' | 'people-access' | 'agents-systems';
type DeliveryTab = 'overview' | 'protocol' | 'tasks' | 'runs';
type ScopeState = Readonly<{project: OperatorProjectSlug | null; environment: string | null; from: string | null; to: string | null}>;
export type PrototypeRoute = Readonly<{area: Area; tab: DeliveryTab; selected: string | null; scope: ScopeState}>;
export type PrototypeData = Readonly<{portfolio: OperatorLoad<PortfolioData>; project: OperatorLoad<ProjectData | null> | null; runs: OperatorLoad<RunsData> | null; access: OperatorLoad<AccessData>; health: OperatorLoad<HealthData> | null}>;

const nav = [
  {area: 'portfolio' as const, label: 'Portfolio', icon: BriefcaseBusiness}, {area: 'delivery' as const, label: 'Delivery', icon: Milestone},
  {area: 'conversations' as const, label: 'Conversations', icon: MessagesSquare}, {area: 'people-access' as const, label: 'People & Access', icon: UsersRound}, {area: 'agents-systems' as const, label: 'Agents & Systems', icon: ServerCog}
];
const deliveryTabs: readonly DeliveryTab[] = ['overview', 'protocol', 'tasks', 'runs'];
const taskStates = ['backlog', 'ready', 'in_dev', 'qa', 'acceptance', 'done'] as const;
const stamp = (value: Date | null | undefined) => value === null || value === undefined ? 'Not observed' : `${value.toISOString().slice(0, 16).replace('T', ' ')} UTC`;
const label = (value: string) => value.replaceAll('_', ' ');
const detail = <T extends Readonly<{id: string}>>(items: readonly T[], id: string | null) => id === null ? null : items.find((item) => item.id === id) ?? null;
const loaded = <T,>(load: OperatorLoad<T> | null): T | null => load?.state === 'ready' ? load.data : null;
const tone = (value: string): 'success' | 'warning' | 'danger' | 'info' | 'neutral' => {
  if (['green', 'done', 'succeeded', 'approved', 'ready'].includes(value)) return 'success';
  if (['red', 'failed', 'blocked', 'rejected', 'expired'].includes(value)) return 'danger';
  if (['yellow', 'pending', 'waiting_approval'].includes(value)) return 'warning';
  if (['running', 'in_dev'].includes(value)) return 'info';
  return 'neutral';
};
const status = (value: string) => <span className={`prototype-status ${tone(value)}`}>{label(value)}</span>;
const query = (scope: ScopeState) => {
  const values = new URLSearchParams();
  if (scope.project !== null) values.set('project', scope.project);
  if (scope.environment !== null) values.set('environment', scope.environment);
  if (scope.from !== null) values.set('from', scope.from);
  if (scope.to !== null) values.set('to', scope.to);
  const result = values.toString(); return result.length === 0 ? '' : `?${result}`;
};
const href = (area: Area, scope: ScopeState, tab: DeliveryTab = 'overview', id?: string | null) => {
  if (area === 'delivery') {
    const segment = (tab === 'tasks' || tab === 'runs') && id !== undefined && id !== null ? `/${id}` : '';
    return `/prototype/delivery/${tab}${segment}${query(scope)}`;
  }
  const segment = area === 'people-access' && id !== undefined && id !== null ? `/${id}` : '';
  return `/prototype/${area}${segment}${query(scope)}`;
};
function Missing({title, children}: Readonly<{title: string; children: ReactNode}>) { return <section className="prototype-missing" aria-live="polite"><CircleHelp aria-hidden="true" size={20}/><div><h2>{title}</h2><p>{children}</p></div></section>; }
function Scope({route}: {route: PrototypeRoute}) {
  const unavailable = route.area === 'people-access' || route.area === 'conversations';
  return <div className="prototype-scope" aria-label="Scope state"><span><b>Project</b>{unavailable ? 'Not applicable' : route.scope.project?.toUpperCase() ?? (route.area === 'portfolio' ? 'All projects' : 'Unknown')}</span><span><b>Environment</b>{unavailable ? 'Not applicable' : 'Not configured'}</span><span><b>Time</b>{unavailable ? 'Not applicable' : 'Not observed'}</span></div>;
}
export function PrototypeShell({route, data}: Readonly<{route: PrototypeRoute; data: PrototypeData}>) {
  const primaryNav = nav.slice(0, 3); const moreNav = nav.slice(3);
  return <main className="prototype-shell"><aside className="prototype-nav"><Link className="prototype-brand" href="/prototype/portfolio">f(AI) Studio</Link><nav aria-label="Workspace">
    {nav.map(({area, label: itemLabel, icon: Icon}) => <Link aria-current={route.area === area ? 'page' : undefined} aria-label={itemLabel} className={route.area === area ? 'prototype-nav-item active' : 'prototype-nav-item'} href={href(area, route.scope)} key={area} title={itemLabel}><Icon aria-hidden="true" size={18}/><span>{itemLabel}</span></Link>)}
  </nav><div className="prototype-mobile-nav" aria-label="Mobile workspace"><nav>{primaryNav.map(({area, label: itemLabel, icon: Icon}) => <Link aria-current={route.area === area ? 'page' : undefined} aria-label={itemLabel} href={href(area, route.scope)} key={area}><Icon aria-hidden="true" size={18}/><span>{itemLabel}</span></Link>)}<details><summary aria-label="More"><MoreHorizontal aria-hidden="true" size={18}/><span>More</span></summary>{moreNav.map(({area, label: itemLabel, icon: Icon}) => <Link aria-label={itemLabel} href={href(area, route.scope)} key={area}><Icon aria-hidden="true" size={17}/><span>{itemLabel}</span></Link>)}</details></nav></div></aside><section className="prototype-content"><header className="prototype-header"><div><p className="prototype-kicker">Operator workspace</p><h1>{nav.find((item) => item.area === route.area)?.label}</h1></div><Scope route={route}/></header>
    {route.area === 'portfolio' ? <Portfolio data={data} route={route}/> : null}{route.area === 'delivery' ? <Delivery data={data} route={route}/> : null}{route.area === 'conversations' ? <Conversations/> : null}{route.area === 'people-access' ? <People data={data} route={route}/> : null}{route.area === 'agents-systems' ? <Systems data={data}/> : null}
  </section></main>;
}
function Portfolio({data, route}: {data: PrototypeData; route: PrototypeRoute}) { const portfolio = loaded(data.portfolio); if (portfolio === null) return <Missing title="Portfolio is unavailable">Project and signal records are unavailable.</Missing>; return <section className="prototype-page"><div className="prototype-row-list" aria-label="Portfolio signals">{portfolio.attention.length === 0 ? <Missing title="Not observed">No unresolved signals are recorded for the configured projects.</Missing> : portfolio.attention.map((signal) => { const project = portfolio.projects.find((item) => item.id === signal.projectId); return <Link className="prototype-row prototype-signal" href={href('delivery', {...route.scope, project: project?.slug ?? null})} key={signal.id}>{status(signal.severity)}<span><strong>{signal.object}</strong><small>{signal.project} · {signal.impact}</small></span><span><strong>{signal.reason}</strong><small>{signal.evidence}</small></span><span><small>Owner</small>{signal.owner ?? 'Unknown'}</span><span><small>Observed</small>{stamp(signal.freshness)}</span><span className="prototype-next">Open delivery</span></Link>; })}</div><section className="prototype-project-strip" aria-labelledby="projects"><h2 id="projects">Projects</h2>{portfolio.projects.map((project) => <Link href={href('delivery', {...route.scope, project: project.slug})} key={project.id}><strong>{project.name}</strong>{status(project.health)}<small>{project.unresolvedRiskCount} unresolved signals · observed {stamp(project.synchronizedAt)}</small></Link>)}</section></section>; }
function Delivery({data, route}: {data: PrototypeData; route: PrototypeRoute}) { const project = loaded(data.project); const runs = loaded(data.runs); if (route.scope.project === null) return <section className="prototype-page"><DeliveryTabs route={route}/><Missing title="Select one project">Delivery requires a concrete project.</Missing></section>; if (project === null) return <section className="prototype-page"><DeliveryTabs route={route}/><Missing title="Not observed">The selected project was not returned.</Missing></section>; return <section className="prototype-page"><DeliveryTabs route={route}/>{route.tab === 'overview' ? <Overview project={project} runs={runs} route={route}/> : route.tab === 'protocol' ? <Protocol/> : route.tab === 'tasks' ? <TaskWorkspace project={project} route={route} runs={runs}/> : <RunWorkspace runs={runs} route={route}/>}</section>; }
function DeliveryTabs({route}: {route: PrototypeRoute}) { return <nav className="prototype-tabs" aria-label="Delivery sections">{deliveryTabs.map((tab) => <Link aria-current={route.tab === tab ? 'page' : undefined} href={href('delivery', route.scope, tab)} key={tab}>{tab}</Link>)}</nav>; }
function Overview({project, runs, route}: {project: ProjectData; runs: RunsData | null; route: PrototypeRoute}) { const knownOwners = new Set(project.workItems.flatMap((item) => item.owner === null ? [] : [item.owner])).size; const receipts = runs?.runs.filter((run) => run.receipt !== null).length ?? 0; return <section className="prototype-overview"><header><p className="prototype-kicker">Delivery summary</p><h2>{project.project.name}</h2></header><ol className="prototype-flow-rail" aria-label="Delivery flow"><li><SquareCheckBig aria-hidden="true" size={17}/><b>Task stage</b><span>{project.workItems.length} recorded</span></li><li><UsersRound aria-hidden="true" size={17}/><b>Responsibility</b><span>{knownOwners === 0 ? 'Unknown' : `${knownOwners} recorded`}</span></li><li><ShieldCheck aria-hidden="true" size={17}/><b>Policy / approval</b><span>{runs?.approvals.length === 0 ? 'Not observed' : `${runs?.approvals.length ?? 0} recorded`}</span></li><li><Activity aria-hidden="true" size={17}/><b>Run</b><span>{runs?.runs.length === 0 ? 'Not observed' : `${runs?.runs.length ?? 0} recorded`}</span></li><li><FileCheck2 aria-hidden="true" size={17}/><b>Receipt</b><span>{receipts === 0 ? 'Not observed' : `${receipts} recorded`}</span></li></ol><FactStrip facts={[["Project record", stamp(project.project.updatedAt)], ["Tracker observation", stamp(project.synchronizedAt)], ["Health snapshot", project.snapshot === null ? 'Not observed' : `${project.snapshot.health} · ${stamp(project.snapshot.capturedAt)}`]]}/><Link className="prototype-action" href={href('delivery', route.scope, 'tasks')}>Open tasks</Link></section>; }
function TaskWorkspace({project, route, runs}: {project: ProjectData; route: PrototypeRoute; runs: RunsData | null}) { const task = detail(project.workItems, route.selected); return <div className="prototype-master-detail"><section className="prototype-master" aria-label="Tasks"><header><p className="prototype-kicker">Delivery / tasks</p><h2>Current work</h2></header>{project.workItems.length === 0 ? <Missing title="Not observed">No work items are recorded.</Missing> : project.workItems.map((item) => <Link className={task?.id === item.id ? 'prototype-task-row selected' : 'prototype-task-row'} href={href('delivery', route.scope, 'tasks', item.id)} key={item.id}><SquareCheckBig aria-hidden="true" size={16}/><span><strong>{item.title}</strong><small>{item.id}</small></span>{status(item.blocked ? 'blocked' : item.status)}<small>{item.owner ?? 'Unknown'}</small></Link>)}</section><TaskDetail project={project} task={task} route={route} runs={runs}/></div>; }
function StageRail({status: current}: {status: string}) { return <ol className="prototype-stage-rail" aria-label="Task stage">{taskStates.map((stage) => <li className={stage === current ? 'current' : taskStates.indexOf(stage) < taskStates.indexOf(current as typeof taskStates[number]) ? 'complete' : ''} key={stage}><span aria-hidden="true"/>{label(stage)}</li>)}</ol>; }
function TaskDetail({project, task, route, runs}: {project: ProjectData; task: ProjectData['workItems'][number] | null; route: PrototypeRoute; runs: RunsData | null}) { if (route.selected === null) return <Missing title="Select a task">Choose a task to open its detail.</Missing>; if (task === null) return <Missing title="Not observed">This task ID is not recorded in the selected project.</Missing>; const associatedRun = task.handoff?.kind === 'run' ? runs?.runs.find((run) => run.id === task.handoff?.targetId) ?? null : null; const runLink = associatedRun === null ? null : href('delivery', route.scope, 'runs', associatedRun.id); return <article className="prototype-detail"><header><p className="prototype-kicker">Task record</p><h2>{task.title}</h2>{status(task.blocked ? 'blocked' : task.status)}</header><StageRail status={task.status}/><FactStrip facts={[["Project", project.project.name], ["Task ID", task.id], ["Responsible human", task.owner ?? 'Unknown'], ["Responsible agent", 'Unknown'], ["Observed execution agent", associatedRun?.agent ?? 'Not observed'], ["Source", task.externalUrl === null ? 'Not observed' : 'Observed via GitHub'], ["Updated", stamp(task.updatedAt)]]}/>{task.summary === null ? null : <p>{task.summary}</p>}<section className="prototype-governance"><header><ShieldCheck aria-hidden="true" size={18}/><div><p className="prototype-kicker">Policy / approval</p><h3>Governed handoff</h3></div></header><FactStrip facts={[["Policy", task.handoff === null ? 'Unknown' : 'Control plane handoff'], ["Approval", task.handoff?.label ?? 'Unknown'], ["Required role", 'Unknown'], ["Action", associatedRun === null ? 'Not observed' : 'Open associated run']]} />{runLink === null ? <p className="prototype-muted">Associated run: Not observed. No unfiltered run link is shown.</p> : <Link className="prototype-action" href={runLink}>Open associated run</Link>}</section><footer>{task.externalUrl === null ? <span>Provider source: Not observed</span> : <a href={task.externalUrl} rel="noreferrer" target="_blank">Observed via GitHub</a>}</footer></article>; }
function Protocol() { return <Missing title="Not configured">No delivery-protocol record is available. Task stages remain visible without inferring a protocol.</Missing>; }
function RunWorkspace({runs, route}: {runs: RunsData | null; route: PrototypeRoute}) { if (runs === null) return <Missing title="Runs are unavailable">Run and approval records are unavailable.</Missing>; const run = detail(runs.runs, route.selected); return <div className="prototype-master-detail"><section className="prototype-master" aria-label="Runs"><header><p className="prototype-kicker">Delivery / runs</p><h2>Run history</h2></header>{runs.runs.length === 0 ? <Missing title="Not observed">No runs are recorded.</Missing> : runs.runs.map((item) => <Link className={run?.id === item.id ? 'prototype-task-row selected' : 'prototype-task-row'} href={href('delivery', route.scope, 'runs', item.id)} key={item.id}><Activity aria-hidden="true" size={16}/><span><strong>{item.workItem ?? 'Unknown task'}</strong><small>{item.id}</small></span>{status(item.status)}<small>{item.agent ?? 'Unknown'}</small></Link>)}</section><RunDetail run={run} approval={run === null ? null : runs.approvals.find((item) => item.agentRunId === run.id) ?? null} selected={route.selected}/></div>; }
function RunDetail({run, approval, selected}: {run: RunsData['runs'][number] | null; approval: RunsData['approvals'][number] | null; selected: string | null}) { if (selected === null) return <Missing title="Select a run">Choose a run to open its receipt.</Missing>; if (run === null) return <Missing title="Not observed">This run ID is not recorded in the selected project.</Missing>; const events = [["Run started", run.startedAt], ["Last heartbeat", run.heartbeatAt], ["Run completed", run.completedAt], ["Receipt recorded", run.receipt?.completedAt ?? null]].filter(([, time]) => time !== null) as [string, Date][]; return <article className="prototype-detail"><header><p className="prototype-kicker">Run record</p><h2>{run.workItem ?? 'Unknown task'}</h2>{status(run.status)}</header><FactStrip facts={[["Run ID", run.id], ["Task ID", run.workItemId ?? 'Unknown'], ["Agent", run.agent ?? 'Unknown'], ["Runtime", run.runtimeProfile], ["Attempt", String(run.attempt)], ["Action", 'Run record']]} /><section className="prototype-governance"><header><ShieldCheck aria-hidden="true" size={18}/><div><p className="prototype-kicker">Policy / approval</p><h3>Decision record</h3></div></header><FactStrip facts={[["Approval ID", approval?.id ?? 'Not observed'], ["Policy version", approval === null ? 'Not observed' : String(approval.policyVersion)], ["Decision", approval?.status ?? 'Not observed'], ["Surface", approval === null ? 'Not observed' : `${approval.actionCategory} · ${approval.surface} · ${approval.environment}`], ["Decided", stamp(approval?.decidedAt)]]}/></section><section><p className="prototype-kicker">Receipt timeline</p><ol className="prototype-receipt">{events.length === 0 ? <li><CircleHelp aria-hidden="true" size={15}/><span>Not observed</span></li> : events.map(([name, time]) => <li key={name}><FileCheck2 aria-hidden="true" size={15}/><span><strong>{name}</strong><small>{stamp(time)}</small></span></li>)}</ol></section><section className="prototype-evidence"><p className="prototype-kicker">Evidence</p>{run.receipt === null ? <p>Receipt: Not observed</p> : <FactStrip facts={[["Terminal", run.receipt.terminal], ["Receipt SHA-256", run.receipt.receiptSha256], ["Receipt time", stamp(run.receipt.completedAt)], ["Duration", run.receipt.durationMs === null ? 'Unknown' : `${(run.receipt.durationMs / 1000).toFixed(1)} seconds`]]}/>}<ul>{run.artifacts.length === 0 ? <li>Artifacts: Not observed</li> : run.artifacts.map((artifact) => <li key={`${artifact.kind}-${artifact.createdAt.toISOString()}`}>{artifact.kind} · {artifact.sizeBytes} bytes · {artifact.redacted ? 'redacted' : 'redaction not observed'} · {stamp(artifact.createdAt)}</li>)}</ul></section><footer><span>Next action: {run.canAcceptReceipt ? 'Accept receipt and move to QA is available in the governed record.' : 'Unknown'}</span><Link href={`/runs?project=${run.projectSlug}#run-${run.id}`}>Open governed record</Link></footer></article>; }
function Conversations() { return <section className="prototype-page"><Missing title="Not configured">No conversation or thread record is available.</Missing></section>; }
function People({route, data}: {route: PrototypeRoute; data: PrototypeData}) { const access = loaded(data.access); if (access === null) return <Missing title="People & Access is unavailable">Actor and policy records are unavailable.</Missing>; const actor = detail(access.actors, route.selected); return <section className="prototype-page prototype-master-detail"><section className="prototype-master"><header><p className="prototype-kicker">Actors</p><h2>People & access</h2></header>{access.actors.length === 0 ? <Missing title="Not observed">No actors are recorded.</Missing> : access.actors.map((item) => <Link className={actor?.id === item.id ? 'prototype-task-row selected' : 'prototype-task-row'} href={href('people-access', route.scope, 'overview', item.id)} key={item.id}><UsersRound aria-hidden="true" size={16}/><span><strong>{item.displayName}</strong><small>{item.id}</small></span>{status(item.disabledAt === null ? 'ready' : 'blocked')}<small>{item.type}</small></Link>)}</section>{route.selected === null ? <Missing title="Select an actor">Choose an actor to open its record.</Missing> : actor === null ? <Missing title="Not observed">This actor ID is not recorded.</Missing> : <article className="prototype-detail"><header><p className="prototype-kicker">Actor record</p><h2>{actor.displayName}</h2></header><FactStrip facts={[["Actor ID", actor.id], ["Type", actor.type], ["Role", actor.role], ["Effective access", 'Unknown'], ["Assignment source", 'Unknown'], ["Status", actor.disabledAt === null ? 'Ready' : `Disabled ${stamp(actor.disabledAt)}`]]}/><section><p className="prototype-kicker">Capabilities</p><ul className="prototype-capabilities">{Object.entries(actor.capabilities).length === 0 ? <li>Not configured</li> : Object.entries(actor.capabilities).map(([key, enabled]) => <li key={key}>{key}: {enabled ? 'enabled' : 'disabled'}</li>)}</ul></section></article>}</section>; }
function Systems({data}: {data: PrototypeData}) { const access = loaded(data.access); const health = loaded(data.health); const configured = access?.hermes ?? null; return <section className="prototype-page"><div className="prototype-system-grid"><article><header><Bot aria-hidden="true" size={19}/><div><p className="prototype-kicker">Agent profile</p><h2>Hermes</h2></div></header>{configured === null ? <p>Not configured</p> : <FactStrip facts={[["Profile ID", configured.id], ["Runtime profile", configured.runtimeProfile], ["Configuration", configured.enabled ? 'Ready' : 'Not configured'], ["Health", 'Not observed'], ["Version", String(configured.version)], ["Configuration hash", configured.configHash]]}/>}</article><article><header><ServerCog aria-hidden="true" size={19}/><div><p className="prototype-kicker">Observed systems</p><h2>Integration observations</h2></div></header>{health === null || health.integrations.length === 0 ? <p>Not observed</p> : <ul className="prototype-system-list">{health.integrations.map((system) => <li key={system.id}><strong>{system.provider}</strong><span>{system.mode} · observed {stamp(system.createdAt)}</span><small>Health: Not observed · {system.id}</small></li>)}</ul>}</article></div></section>; }
function FactStrip({facts}: {facts: readonly (readonly [string, string])[]}) { return <dl className="prototype-facts">{facts.map(([term, value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl>; }
